apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: {{ .Values.labels }}
  ports:
    - name: http
      port: {{ .Values.configuration.server.port }}
      targetPort: http
