ALTER TABLE articles
    ADD COLUMN IF NOT EXISTS images_requested INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS images_resolved  INTEGER NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS images_skipped   INTEGER NOT NULL DEFAULT 0;
