ALTER TABLE users DROP CONSTRAINT IF EXISTS users_advocate_link_check;
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users DROP COLUMN IF EXISTS advocate_id;
ALTER TABLE users DROP COLUMN IF EXISTS role;
