// Package oapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapigen

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for HealthResponseStatus.
const (
	Degraded HealthResponseStatus = "degraded"
	Ok       HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for RateArticleRequestRating.
const (
	Dislike RateArticleRequestRating = "dislike"
	Like    RateArticleRequestRating = "like"
	None    RateArticleRequestRating = "none"
)

// Valid indicates whether the value is a known member of the RateArticleRequestRating enum.
func (e RateArticleRequestRating) Valid() bool {
	switch e {
	case Dislike:
		return true
	case Like:
		return true
	case None:
		return true
	default:
		return false
	}
}

// Defines values for SiteProvider.
const (
	Modx      SiteProvider = "modx"
	Wordpress SiteProvider = "wordpress"
)

// Valid indicates whether the value is a known member of the SiteProvider enum.
func (e SiteProvider) Valid() bool {
	switch e {
	case Modx:
		return true
	case Wordpress:
		return true
	default:
		return false
	}
}

// Defines values for GetLeadStatsParamsGroupBy.
const (
	Day   GetLeadStatsParamsGroupBy = "day"
	Month GetLeadStatsParamsGroupBy = "month"
)

// Valid indicates whether the value is a known member of the GetLeadStatsParamsGroupBy enum.
func (e GetLeadStatsParamsGroupBy) Valid() bool {
	switch e {
	case Day:
		return true
	case Month:
		return true
	default:
		return false
	}
}

// ApiToken defines model for ApiToken.
type ApiToken struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Prefix    string             `json:"prefix"`
}

// ApiTokenCreated defines model for ApiTokenCreated.
type ApiTokenCreated struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Prefix    string             `json:"prefix"`
	Token     string             `json:"token"`
}

// Article defines model for Article.
type Article struct {
	AiScore         *float32            `json:"ai_score,omitempty"`
	CheckResult     *json.RawMessage    `json:"check_result,omitempty"`
	CompetitorData  *json.RawMessage    `json:"competitor_data,omitempty"`
	CreatedAt       time.Time           `json:"created_at"`
	HumanRating     *bool               `json:"human_rating,omitempty"`
	HumanizeCycles  *int                `json:"humanize_cycles,omitempty"`
	Id              int64               `json:"id"`
	ImagesRequested *int                `json:"images_requested,omitempty"`
	ImagesResolved  *int                `json:"images_resolved,omitempty"`
	ImagesSkipped   *int                `json:"images_skipped,omitempty"`
	Keyword         string              `json:"keyword"`
	PublishedAt     *time.Time          `json:"published_at,omitempty"`
	QualityOk       *bool               `json:"quality_ok,omitempty"`
	RequestParams   *json.RawMessage    `json:"request_params,omitempty"`
	Reward          *float32            `json:"reward,omitempty"`
	Site            *string             `json:"site,omitempty"`
	SiteId          *openapi_types.UUID `json:"site_id,omitempty"`
	Status          string              `json:"status"`
	Tokens          *int                `json:"tokens,omitempty"`
	UpdatedAt       time.Time           `json:"updated_at"`
	WpEditUrl       *string             `json:"wp_edit_url,omitempty"`
	WpPostId        *int64              `json:"wp_post_id,omitempty"`
	WpPostUrl       *string             `json:"wp_post_url,omitempty"`
}

// ArticleList defines model for ArticleList.
type ArticleList struct {
	Items []Article `json:"items"`
	Total int64     `json:"total"`
}

// CreateApiTokenRequest defines model for CreateApiTokenRequest.
type CreateApiTokenRequest struct {
	Name string `json:"name" validate:"required,min=1,max=100"`
}

// CreateWordpressSiteRequest defines model for CreateWordpressSiteRequest.
type CreateWordpressSiteRequest struct {
	Alias       string                    `json:"alias" validate:"required,min=1,max=100"`
	AppPassword *string                   `json:"appPassword,omitempty" validate:"required"`
	Languages   map[string]LanguageConfig `json:"languages,omitempty"`
	Provider    SiteProvider              `json:"provider" validate:"required,oneof=wordpress modx"`
	Url         string                    `json:"url" validate:"required,url"`
	Username    *string                   `json:"username,omitempty" validate:"required_if=Provider wordpress,omitempty,max=255"`
}

// ErrorResponse RFC 7807 problem details
type ErrorResponse struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     *string `json:"type,omitempty"`
}

// GenerateAccepted defines model for GenerateAccepted.
type GenerateAccepted struct {
	CreatedAt      time.Time           `json:"created_at"`
	Id             int64               `json:"id"`
	Keyword        string              `json:"keyword"`
	Model          *string             `json:"model,omitempty"`
	Provider       *string             `json:"provider,omitempty"`
	Site           *string             `json:"site,omitempty"`
	SiteId         *openapi_types.UUID `json:"site_id,omitempty"`
	Status         string              `json:"status"`
	StatusUrl      *string             `json:"status_url,omitempty"`
	SuggestedTitle *string             `json:"suggested_title,omitempty"`
	TargetKeywords []string            `json:"target_keywords,omitempty"`
}

// GenerateBatchAccepted defines model for GenerateBatchAccepted.
type GenerateBatchAccepted struct {
	ArticleIds []int64 `json:"article_ids"`
	Count      int     `json:"count"`
}

// GenerateBatchRequest defines model for GenerateBatchRequest.
type GenerateBatchRequest struct {
	AiThreshold   *float32           `json:"ai_threshold,omitempty"`
	AutoPublish   *bool              `json:"auto_publish,omitempty"`
	Count         int                `json:"count" validate:"required,min=1,max=100"`
	IncludeImages *bool              `json:"include_images,omitempty"`
	Language      *string            `json:"language,omitempty"`
	MaxCycles     *int               `json:"max_cycles,omitempty"`
	MaxTokens     *int               `json:"max_tokens,omitempty"`
	MaxWords      *int               `json:"max_words,omitempty"`
	MinWords      *int               `json:"min_words,omitempty"`
	Model         *string            `json:"model,omitempty"`
	Provider      *string            `json:"provider,omitempty"`
	SiteId        openapi_types.UUID `json:"site_id" validate:"required"`
}

// GenerateRequest defines model for GenerateRequest.
type GenerateRequest struct {
	AiThreshold             *float32           `json:"ai_threshold,omitempty"`
	AutoPublish             *bool              `json:"auto_publish,omitempty"`
	ExtraRules              *string            `json:"extra_rules,omitempty"`
	IncludeImageAttribution *bool              `json:"include_image_attribution,omitempty"`
	IncludeImages           *bool              `json:"include_images,omitempty"`
	Keyword                 string             `json:"keyword" validate:"required,min=1,max=200"`
	Language                *string            `json:"language,omitempty"`
	MaxCycles               *int               `json:"max_cycles,omitempty"`
	MaxTokens               *int               `json:"max_tokens,omitempty"`
	MaxWords                *int               `json:"max_words,omitempty"`
	MinWords                *int               `json:"min_words,omitempty"`
	Model                   *string            `json:"model,omitempty"`
	Provider                *string            `json:"provider,omitempty"`
	SiteId                  openapi_types.UUID `json:"site_id" validate:"required"`
	SiteTopic               *string            `json:"site_topic,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
	Time   time.Time            `json:"time"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// LanguageConfig Per-language settings for a bilingual site — which MODX context a language publishes into, and which keyword sheet (if any) supplies its generation topics.
type LanguageConfig struct {
	ContextKey            *string `json:"contextKey,omitempty"`
	KeywordsSheet         *string `json:"keywordsSheet,omitempty"`
	KeywordsSpreadsheetId *string `json:"keywordsSpreadsheetId,omitempty"`
}

// LeadStats defines model for LeadStats.
type LeadStats struct {
	ByCreator []LeadStatsCreatorRevenue `json:"by_creator"`
	ByPage    []LeadStatsCount          `json:"by_page"`
	ByStatus  []LeadStatsCount          `json:"by_status"`
	Range     struct {
		From    openapi_types.Date `json:"from"`
		GroupBy string             `json:"group_by"`
		To      openapi_types.Date `json:"to"`
	} `json:"range"`
	Totals struct {
		AvgTicket         float32 `json:"avg_ticket"`
		CaseFeeContracted float32 `json:"case_fee_contracted"`
		CaseOwed          float32 `json:"case_owed"`
		CasePaid          float32 `json:"case_paid"`
		CasesCompleted    int64   `json:"cases_completed"`
		CasesInProgress   int64   `json:"cases_in_progress"`
		Clients           int64   `json:"clients"`
		Consultations     int64   `json:"consultations"`
		Leads             int64   `json:"leads"`
		RevenueBooked     float32 `json:"revenue_booked"`
		RevenueEarned     float32 `json:"revenue_earned"`
		RevenueLost       float32 `json:"revenue_lost"`
	} `json:"totals"`
	Trend []LeadStatsBucket `json:"trend"`
}

// LeadStatsBucket defines model for LeadStatsBucket.
type LeadStatsBucket struct {
	Bucket        string  `json:"bucket"`
	Consultations int64   `json:"consultations"`
	Leads         int64   `json:"leads"`
	RevenueEarned float32 `json:"revenue_earned"`
}

// LeadStatsCount defines model for LeadStatsCount.
type LeadStatsCount struct {
	Count int64  `json:"count"`
	Key   string `json:"key"`
}

// LeadStatsCreatorRevenue defines model for LeadStatsCreatorRevenue.
type LeadStatsCreatorRevenue struct {
	Bookings      int64   `json:"bookings"`
	Key           string  `json:"key"`
	RevenueEarned float32 `json:"revenue_earned"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required,min=1"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Token     string    `json:"token"`
}

// PlaceBacklinksAccepted defines model for PlaceBacklinksAccepted.
type PlaceBacklinksAccepted struct {
	RunId       string `json:"run_id"`
	Sheet       string `json:"sheet"`
	SitesQueued int    `json:"sites_queued"`
}

// PlaceBacklinksRequest defines model for PlaceBacklinksRequest.
type PlaceBacklinksRequest struct {
	// Count Stop after this many SUCCESSFUL placements (failures don't count). Defaults to 3 when omitted.
	Count *int `json:"count,omitempty"`

	// Model Override the default LLM model for this run only. Falls back to LLM_BACKLINK_MODEL (or LLM_MODEL) when empty.
	Model *string `json:"model,omitempty"`

	// Provider Override the default LLM provider for this run only. Falls back to LLM_BACKLINK_PROVIDER (or LLM_PROVIDER) when empty.
	Provider *string `json:"provider,omitempty"`
	Sheet    string  `json:"sheet" validate:"required,min=1"`

	// TargetSiteUrl Public URL of one of the user's wordpress_sites; the backend rejects URLs not present in that table.
	TargetSiteUrl string `json:"target_site_url" validate:"required,url"`
}

// Placement defines model for Placement.
type Placement struct {
	Anchor    *string   `json:"anchor,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	DonorUrl  string    `json:"donor_url"`
	EditUrl   *string   `json:"edit_url,omitempty"`
	Id        int64     `json:"id"`
	Ok        bool      `json:"ok"`
	Outcome   *string   `json:"outcome,omitempty"`
	PostUrl   *string   `json:"post_url,omitempty"`
	Status    string    `json:"status"`
	TargetUrl string    `json:"target_url"`
}

// PlacementList defines model for PlacementList.
type PlacementList struct {
	Items []Placement `json:"items"`
	Total int         `json:"total"`
}

// RateArticleRequest defines model for RateArticleRequest.
type RateArticleRequest struct {
	Rating RateArticleRequestRating `json:"rating"`
}

// RateArticleRequestRating defines model for RateArticleRequest.Rating.
type RateArticleRequestRating string

// ScrapeEmailsAccepted defines model for ScrapeEmailsAccepted.
type ScrapeEmailsAccepted struct {
	JobId       string `json:"job_id"`
	Sheet       string `json:"sheet"`
	SitesQueued int    `json:"sites_queued"`
}

// ScrapeEmailsRequest defines model for ScrapeEmailsRequest.
type ScrapeEmailsRequest struct {
	Sheet string `json:"sheet" validate:"required,min=1"`
}

// ScrapeJob defines model for ScrapeJob.
type ScrapeJob struct {
	Id        string `json:"id"`
	Processed int    `json:"processed"`
	Sheet     string `json:"sheet"`
	State     string `json:"state"`
	Total     int    `json:"total"`
}

// SiteProvider defines model for SiteProvider.
type SiteProvider string

// UpdateWordpressSiteRequest defines model for UpdateWordpressSiteRequest.
type UpdateWordpressSiteRequest struct {
	Alias       *string                   `json:"alias,omitempty" validate:"omitempty,min=1,max=100"`
	AppPassword *string                   `json:"appPassword,omitempty"`
	Enabled     *bool                     `json:"enabled,omitempty"`
	Languages   map[string]LanguageConfig `json:"languages,omitempty"`
	Url         *string                   `json:"url,omitempty" validate:"omitempty,url"`
	Username    *string                   `json:"username,omitempty" validate:"omitempty,max=255"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time          `json:"createdAt"`
	Email     string             `json:"email"`
	Id        openapi_types.UUID `json:"id"`
}

// WordpressSite defines model for WordpressSite.
type WordpressSite struct {
	Alias     string                    `json:"alias"`
	CreatedAt time.Time                 `json:"createdAt"`
	Enabled   bool                      `json:"enabled"`
	Id        openapi_types.UUID        `json:"id"`
	Languages map[string]LanguageConfig `json:"languages,omitempty"`
	Provider  SiteProvider              `json:"provider"`
	UpdatedAt time.Time                 `json:"updatedAt"`
	Url       string                    `json:"url"`
	Username  string                    `json:"username"`
}

// BadRequest RFC 7807 problem details
type BadRequest = ErrorResponse

// Conflict RFC 7807 problem details
type Conflict = ErrorResponse

// NotFound RFC 7807 problem details
type NotFound = ErrorResponse

// Unauthorized RFC 7807 problem details
type Unauthorized = ErrorResponse

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListArticlesParams defines parameters for ListArticles.
type ListArticlesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetLeadStatsParams defines parameters for GetLeadStats.
type GetLeadStatsParams struct {
	From    openapi_types.Date         `form:"from" json:"from"`
	To      openapi_types.Date         `form:"to" json:"to"`
	GroupBy *GetLeadStatsParamsGroupBy `form:"group_by,omitempty" json:"group_by,omitempty"`
}

// GetLeadStatsParamsGroupBy defines parameters for GetLeadStats.
type GetLeadStatsParamsGroupBy string

// ListPlacementsParams defines parameters for ListPlacements.
type ListPlacementsParams struct {
	RunId string `form:"run_id" json:"run_id"`
}

// ListPlacementHistoryParams defines parameters for ListPlacementHistory.
type ListPlacementHistoryParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateApiTokenJSONRequestBody defines body for CreateApiToken for application/json ContentType.
type CreateApiTokenJSONRequestBody = CreateApiTokenRequest

// RateArticleJSONRequestBody defines body for RateArticle for application/json ContentType.
type RateArticleJSONRequestBody = RateArticleRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ScrapeEmailsJSONRequestBody defines body for ScrapeEmails for application/json ContentType.
type ScrapeEmailsJSONRequestBody = ScrapeEmailsRequest

// GenerateArticleJSONRequestBody defines body for GenerateArticle for application/json ContentType.
type GenerateArticleJSONRequestBody = GenerateRequest

// GenerateBatchJSONRequestBody defines body for GenerateBatch for application/json ContentType.
type GenerateBatchJSONRequestBody = GenerateBatchRequest

// PlaceBacklinksJSONRequestBody defines body for PlaceBacklinks for application/json ContentType.
type PlaceBacklinksJSONRequestBody = PlaceBacklinksRequest

// CreateWordpressSiteJSONRequestBody defines body for CreateWordpressSite for application/json ContentType.
type CreateWordpressSiteJSONRequestBody = CreateWordpressSiteRequest

// UpdateWordpressSiteJSONRequestBody defines body for UpdateWordpressSite for application/json ContentType.
type UpdateWordpressSiteJSONRequestBody = UpdateWordpressSiteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List your API tokens (metadata only)
	// (GET /api-tokens)
	ListApiTokens(w http.ResponseWriter, r *http.Request)
	// Create an API token (the secret is returned only once)
	// (POST /api-tokens)
	CreateApiToken(w http.ResponseWriter, r *http.Request)
	// Revoke an API token
	// (DELETE /api-tokens/{id})
	DeleteApiToken(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List articles (paginated, newest first)
	// (GET /articles)
	ListArticles(w http.ResponseWriter, r *http.Request, params ListArticlesParams)
	// Get an article
	// (GET /articles/{id})
	GetArticle(w http.ResponseWriter, r *http.Request, id int64)
	// Publish a draft article
	// (POST /articles/{id}/publish)
	PublishArticle(w http.ResponseWriter, r *http.Request, id int64)
	// Rate an article (copywriter 👍/👎)
	// (POST /articles/{id}/rating)
	RateArticle(w http.ResponseWriter, r *http.Request, id int64)
	// Authenticate and receive a JWT
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Crawl the sites listed in a sheet and scrape their email addresses
	// (POST /emailscrape)
	ScrapeEmails(w http.ResponseWriter, r *http.Request)
	// Get the progress and state of a scrape job
	// (GET /emailscrape/jobs/{id})
	GetScrapeJob(w http.ResponseWriter, r *http.Request, id string)
	// Request cancellation of a running scrape job
	// (POST /emailscrape/jobs/{id}/cancel)
	CancelScrapeJob(w http.ResponseWriter, r *http.Request, id string)
	// Queue an article for generation
	// (POST /generate)
	GenerateArticle(w http.ResponseWriter, r *http.Request)
	// Queue a batch from the next N unused sheet topics
	// (POST /generate/batch)
	GenerateBatch(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// Aggregate lead/consultation stats over a date range, for the admin dashboard
	// (GET /leads/stats)
	GetLeadStats(w http.ResponseWriter, r *http.Request, params GetLeadStatsParams)
	// Place a backlink to one of our WordPress sites in each suitable donor's latest post
	// (POST /linkbuilding/place-backlinks)
	PlaceBacklinks(w http.ResponseWriter, r *http.Request)
	// Per-donor results of a placement run
	// (GET /linkbuilding/placements)
	ListPlacements(w http.ResponseWriter, r *http.Request, params ListPlacementsParams)
	// Successful placements across all runs (paginated, newest first)
	// (GET /linkbuilding/placements/history)
	ListPlacementHistory(w http.ResponseWriter, r *http.Request, params ListPlacementHistoryParams)
	// Request cancellation of a running placement
	// (POST /linkbuilding/placements/{run_id}/cancel)
	CancelPlacement(w http.ResponseWriter, r *http.Request, runId string)
	// List users
	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request)
	// List WordPress sites
	// (GET /wordpress-sites)
	ListWordpressSites(w http.ResponseWriter, r *http.Request)
	// Add a WordPress site
	// (POST /wordpress-sites)
	CreateWordpressSite(w http.ResponseWriter, r *http.Request)
	// Soft-delete a WordPress site
	// (DELETE /wordpress-sites/{id})
	DeleteWordpressSite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get a WordPress site
	// (GET /wordpress-sites/{id})
	GetWordpressSite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update a WordPress site
	// (PATCH /wordpress-sites/{id})
	UpdateWordpressSite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List your API tokens (metadata only)
// (GET /api-tokens)
func (_ Unimplemented) ListApiTokens(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an API token (the secret is returned only once)
// (POST /api-tokens)
func (_ Unimplemented) CreateApiToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke an API token
// (DELETE /api-tokens/{id})
func (_ Unimplemented) DeleteApiToken(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List articles (paginated, newest first)
// (GET /articles)
func (_ Unimplemented) ListArticles(w http.ResponseWriter, r *http.Request, params ListArticlesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get an article
// (GET /articles/{id})
func (_ Unimplemented) GetArticle(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Publish a draft article
// (POST /articles/{id}/publish)
func (_ Unimplemented) PublishArticle(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rate an article (copywriter 👍/👎)
// (POST /articles/{id}/rating)
func (_ Unimplemented) RateArticle(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Authenticate and receive a JWT
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Crawl the sites listed in a sheet and scrape their email addresses
// (POST /emailscrape)
func (_ Unimplemented) ScrapeEmails(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the progress and state of a scrape job
// (GET /emailscrape/jobs/{id})
func (_ Unimplemented) GetScrapeJob(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request cancellation of a running scrape job
// (POST /emailscrape/jobs/{id}/cancel)
func (_ Unimplemented) CancelScrapeJob(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Queue an article for generation
// (POST /generate)
func (_ Unimplemented) GenerateArticle(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Queue a batch from the next N unused sheet topics
// (POST /generate/batch)
func (_ Unimplemented) GenerateBatch(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Aggregate lead/consultation stats over a date range, for the admin dashboard
// (GET /leads/stats)
func (_ Unimplemented) GetLeadStats(w http.ResponseWriter, r *http.Request, params GetLeadStatsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Place a backlink to one of our WordPress sites in each suitable donor's latest post
// (POST /linkbuilding/place-backlinks)
func (_ Unimplemented) PlaceBacklinks(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Per-donor results of a placement run
// (GET /linkbuilding/placements)
func (_ Unimplemented) ListPlacements(w http.ResponseWriter, r *http.Request, params ListPlacementsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Successful placements across all runs (paginated, newest first)
// (GET /linkbuilding/placements/history)
func (_ Unimplemented) ListPlacementHistory(w http.ResponseWriter, r *http.Request, params ListPlacementHistoryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request cancellation of a running placement
// (POST /linkbuilding/placements/{run_id}/cancel)
func (_ Unimplemented) CancelPlacement(w http.ResponseWriter, r *http.Request, runId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List users
// (GET /users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List WordPress sites
// (GET /wordpress-sites)
func (_ Unimplemented) ListWordpressSites(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a WordPress site
// (POST /wordpress-sites)
func (_ Unimplemented) CreateWordpressSite(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Soft-delete a WordPress site
// (DELETE /wordpress-sites/{id})
func (_ Unimplemented) DeleteWordpressSite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a WordPress site
// (GET /wordpress-sites/{id})
func (_ Unimplemented) GetWordpressSite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a WordPress site
// (PATCH /wordpress-sites/{id})
func (_ Unimplemented) UpdateWordpressSite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListApiTokens operation middleware
func (siw *ServerInterfaceWrapper) ListApiTokens(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApiTokens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateApiToken operation middleware
func (siw *ServerInterfaceWrapper) CreateApiToken(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateApiToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiToken operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiToken(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiToken(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListArticles operation middleware
func (siw *ServerInterfaceWrapper) ListArticles(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListArticlesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListArticles(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArticle operation middleware
func (siw *ServerInterfaceWrapper) GetArticle(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArticle(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PublishArticle operation middleware
func (siw *ServerInterfaceWrapper) PublishArticle(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PublishArticle(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RateArticle operation middleware
func (siw *ServerInterfaceWrapper) RateArticle(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RateArticle(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ScrapeEmails operation middleware
func (siw *ServerInterfaceWrapper) ScrapeEmails(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ScrapeEmails(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetScrapeJob operation middleware
func (siw *ServerInterfaceWrapper) GetScrapeJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetScrapeJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelScrapeJob operation middleware
func (siw *ServerInterfaceWrapper) CancelScrapeJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelScrapeJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateArticle operation middleware
func (siw *ServerInterfaceWrapper) GenerateArticle(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateArticle(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateBatch operation middleware
func (siw *ServerInterfaceWrapper) GenerateBatch(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateBatch(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLeadStats operation middleware
func (siw *ServerInterfaceWrapper) GetLeadStats(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLeadStatsParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "group_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "group_by", r.URL.Query(), &params.GroupBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "group_by"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "group_by", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLeadStats(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlaceBacklinks operation middleware
func (siw *ServerInterfaceWrapper) PlaceBacklinks(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlaceBacklinks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPlacements operation middleware
func (siw *ServerInterfaceWrapper) ListPlacements(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPlacementsParams

	// ------------- Required query parameter "run_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "run_id", r.URL.Query(), &params.RunId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "run_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "run_id", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPlacements(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPlacementHistory operation middleware
func (siw *ServerInterfaceWrapper) ListPlacementHistory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPlacementHistoryParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPlacementHistory(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelPlacement operation middleware
func (siw *ServerInterfaceWrapper) CancelPlacement(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "run_id" -------------
	var runId string

	err = runtime.BindStyledParameterWithOptions("simple", "run_id", chi.URLParam(r, "run_id"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "run_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelPlacement(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWordpressSites operation middleware
func (siw *ServerInterfaceWrapper) ListWordpressSites(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWordpressSites(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWordpressSite operation middleware
func (siw *ServerInterfaceWrapper) CreateWordpressSite(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWordpressSite(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteWordpressSite operation middleware
func (siw *ServerInterfaceWrapper) DeleteWordpressSite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteWordpressSite(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWordpressSite operation middleware
func (siw *ServerInterfaceWrapper) GetWordpressSite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWordpressSite(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateWordpressSite operation middleware
func (siw *ServerInterfaceWrapper) UpdateWordpressSite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateWordpressSite(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api-tokens", wrapper.ListApiTokens)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api-tokens", wrapper.CreateApiToken)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api-tokens/{id}", wrapper.DeleteApiToken)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/articles", wrapper.ListArticles)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/articles/{id}", wrapper.GetArticle)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/articles/{id}/publish", wrapper.PublishArticle)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/articles/{id}/rating", wrapper.RateArticle)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/emailscrape", wrapper.ScrapeEmails)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/emailscrape/jobs/{id}", wrapper.GetScrapeJob)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/emailscrape/jobs/{id}/cancel", wrapper.CancelScrapeJob)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/generate", wrapper.GenerateArticle)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/generate/batch", wrapper.GenerateBatch)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/leads/stats", wrapper.GetLeadStats)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/linkbuilding/place-backlinks", wrapper.PlaceBacklinks)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/linkbuilding/placements", wrapper.ListPlacements)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/linkbuilding/placements/history", wrapper.ListPlacementHistory)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/linkbuilding/placements/{run_id}/cancel", wrapper.CancelPlacement)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/wordpress-sites", wrapper.ListWordpressSites)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/wordpress-sites", wrapper.CreateWordpressSite)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/wordpress-sites/{id}", wrapper.DeleteWordpressSite)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/wordpress-sites/{id}", wrapper.GetWordpressSite)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/wordpress-sites/{id}", wrapper.UpdateWordpressSite)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fzvbhw5cn8VohPAMjLSyPZu7qLDfpBl2atdeaVI62yCjdDgdNf00GKTvSRbo1lDQF4gAQ7I93u3PME9",
	"QsA//Z/d0yPNyBcgn9aaJovFqh+rilXF/RJEPM04A6ZkcPQlECAzziSYP97i+Ap+y0Eq/VfEmQJm/omz",
	"jJIIK8LZNBN8RiH9h8+SM/1NRgtIsf7X3wuYB0fB302rJab2q5yeCsHFlVsseHh4mAQxyEiQTBMNjoIz",
	"docpiZFwDDxMghPO5pREX4GZYmW0JGqB4J5IRViCBEieiwg0cz9x9Z7nLH5+5q4cF4hxheaGh4dJ8Inh",
	"XC24IL/DV+DpI5FSS4gLRJwiZ4AFCKT4LbBAz3DE9FrHGfnZ/H70JcgEz0AoYiEYCcAK4mPD+JyLFKvg",
	"KIixgn1FUggmgVplEBwFUgnCEr1zEjfG5jmJfcMYTkEP7HzIBMzJvefTwyTQaCRCS/TXwJA1VMo5kxq/",
	"N+WafPYZIoPgYp8ndtTf9nYngSp08ghB2LlrBSIUiSh0BYFJKCMuzBeWU4pnepQSOZRUWJ7OQGgq0QKi",
	"21CAzKkamOCWnQT3+wnfdz9q4B9c4eVHkBIn5ihrwIMiioswxgpvg6IVQog30OsiTzELBdaWZoCFGecU",
	"MCtnkN8hjFYRtWLsmUSYgsTKrgUfwtQ/fhN4B6Y4ARk6e2zBOzBKcnq3ZpC8JVnWN+YWVksuYj9k8xkl",
	"cjEs0J6tV1R+yzElahXy23HidTsPMyxwKreACgFLbHe4FuGSKP/p1R9CvwlYKwCpsMpl/8kfiaA8izcG",
	"9zILISYqzAX1rr/MwoxLFY5GZzHBT9BnsAqAlXJoHNPGtgYs1zmxwVHTehEFafMfQ960MIIP5TJYCLyy",
	"elCYjhJBe4tm4YKAbwPWBxUeqRbnNbfi9xsa2xxnZD/iMSTA9uFeCbyvcGImGY+PNWRLpiYpYd+9mqT4",
	"/rtXh4c2ZqgzbNbp5/MXLuJMgJTXREEvs5gSLHfC7URHTZdYSr9R2nwFQ5NiluTaFhrm45jo8AnTy8am",
	"hqBz7gjoAJUkNQRV8ssEvyMxCCsfejEPjn4dJqpFfFnMerh5hPQ4Az7/blnoDKU8vjcb9h7PRyyg6Rh6",
	"EsS2EBqS+XfFtlHJ+4Sn+ixlamXQ8Prbb7vYtbCridpu1IfmZuR89KUdy78/QX/44+EfkIvLUQwKE+qI",
	"10Bhf/faTsKkwizq8Rdtm1+zoYoo6p9lf1hnVu38cg3f9j8AA6HNThRBNhQBb+RNRnuJoaAi5THQngi5",
	"OkFeB/ycntl+6nWcMk8SE56FA9rEIgEVOmE0/VSP6guPtLkjHULBW6yiRT8UsPWLIWnxOELRbT8a8dze",
	"fde4TTtu0lh67Q763REJ1UKAXHBax1wV1uFc8dBFs7UBtaCzj/GtuDTCIprHENp4fFwUXLgs/xnC97XL",
	"R1ct+nsVWvq/l5j0fCZs8PPjT3A45hb9KCffA7Bi0SFw7RJXhvVQ5E1V1Z1IDRohVkqQWW6d1BiUPAZZ",
	"vcb5SVh/7bD+/7jdNDg19BXPSLTe9dd8wACwvwdM1aIe/TRxXbk9YHmq6fLbYBLEkAgcQ51mzT8RG/2N",
	"iRRaTJfuyoz2MdwKrzvh2iWI/QJYSIJShCUSzblAGM0IJfoLRVok6H/+47/RckGiBfp48e5fkUnH3iuE",
	"UTm/yGpIRJjiE4RZ7GY46SK5AFBoj8wRZquXSOZZRokeryRKrNEgnCGjM3nw76wTNbpVf4SVF1FFRHCt",
	"1xkekQnAseHnLPbDoytMwPG1wrbO0ORrtgpNyMDF6EtzSe3ETryCO2C59xI9W4WZO/kbkjbG2k+xwuqW",
	"aArMEs+ZmAuedvDtC4ITwfMsnK168jkjaLSOh1nZTK0R950Sk2PwaBXfJaEi0W0DS7WsLZYQzgFCjUqB",
	"o2ZOsTWOL4e+Zpj0f5Wh1gcFR39E9GhnERZmgif6Ejh2HiVFHW3MaM5kTpU5s2PnUH3qRo4V9kSEM85v",
	"e4RXDAEs2JohlEufGluYsfxVkmjvssNVh4fWipM6inya6erYj6w6UuqY8gJagC3kbXa03+aGy3WXJnvQ",
	"y2NTLFfZqUndHtaNzc2QVXWrd21r3jqBlVV4LgT2wqslGcfqpIJRD3gcwUF5nBQ3p7YLdD+PSxeMCn2C",
	"4p42zFDTUXUVxfmtjh+exNzmQrf8l4uPEzJPSH/KGFJvauoRYbylpDnOtph6tbeD7t3MrlZba2DrfSEs",
	"3GdEgNykgDuyyloUVKsVfOxdUhzBWxzdUsJuZX9uReQsJP5EmOyN/nQgK8Pfcsj9Vbt2fG0ItaZNiqXX",
	"c98LsPIMN6Pxa8UzhOcKBFILIlGK2Qpdfzo5Ob2+fv/pHGWaeqptN9qbY0JzARLFnL1QyFB8eYDewRzn",
	"VEmkOHqDlgtgiKdEKYgPjOixdjLB0ZvJ0DWuydXFHQhBYkBqASi29NH5+UdkxpvLguFW5AxxRlcH6D2m",
	"VKIZjm41G+fnH8O3xyc/np/99GP48eLd6Tna48L8bP56adk0KeoDH77ql8iRrBVTNuTu8uriX87enV6V",
	"DBY/tHksBRlEFOex91iUMKwG/3L69vrs59PrLdxwSxtQpkPNxdWlVVu3PH0xi9Cnq3PE54gz0P/RIssl",
	"iBeyqhUYGvJP5psWELAYCdDglnq2NB06eiQwhQhDaoEVUnhGoSmUhVKZPJpOM4pXWU4lHCiIFsGkds8X",
	"ZBtCsGWUnmPblkvvgU3B52gxixbcn7l4TI4/5oyL3rT3YDF5dHnAdgJ0M1M8VxHva5/przoPV9itdMfX",
	"qysBNCZPbI5kbOq9VNg2CteV9odK10+uVF9hBa5G3usSqj6ZInVEya0GUkyk+xfjDDwppE50bgj5+LiO",
	"BM7gVEcJA571M599Lc/qll7He68QPSb33cVPF1dbNbjerfSz/AOfeWAa96VLI5Cyr6VoQPwK91TxRqPY",
	"5D4LtSiXXzGT63x591kvt9cAXLqVwMQW99705yfTpfJM3RG1Uvhm7RHaQjPt52K/gX2OPognth5Ue99m",
	"70FPc0GH+U/SYuPJ3aI9d7OxfaQ+1BfXpuFOzwZER2PzYfKoTQ5hbWS/7HO35oxvyClb0zYRiUP/YAA5",
	"iGmv6nsaX2p0KmXUNVnfQhcs2iBDlAuiVtdaAi49YvrHj3O1qP56X2znh19+DlxHuVG3+VptUAfU9mQR",
	"NufdCP/4DF2fXiDXI1+vpWQUKy00c7OyHRXBiR32nvIlOr48CybBHQhpKR0evDo4NDFjBgxnJDgK3hwc",
	"HrwxaQW1MDuZatNQlRMT65Q0rsyaZ3FwFOjwrOjNs0mZ2ruM14eHAy393Vb+cV2IRQ9+N3/Zae//N54L",
	"hCNF7gC5jdS1ZjrM6vr69ebhZhLIPE2xWLndoZUmcnx55iigvRQUjrHC5qL50oS52mD+GuhBThI3LuTu",
	"SqzZzxiU/bpvebzaSFpDQvI3TbaCGiVyeOio7NXWmGi/IvA9WLGfTNVR4jt7wzdyRowvJ4goFGH2QqEZ",
	"IAFKELiDGFGsrIH5xgLMx0S5q2ntddBGyre8Icwq5aM9zZ+ESIBCRGqWcsEgNkhAnEXQC4eHSf08Tb+Q",
	"+MGebwrWzzRR8s783kBJQ0vfeHry4M6UKoxcvlkvl/Il0EZSsas0pDJwArDAKSgQ0tAlmk1tXop3GEfW",
	"PDchOanBa52bvzFitXeuNUaqGOTn6rccxKpii5KUqKDOiUs7BUevv/U1NfvJ8PlcQg+dQw+Zmyca0BHd",
	"2+Y+7TmJxyjDickYFeKcIAZLkArNidj07BjDWRBCexlOCNMHvUmzcVgK/bij4v4sD4pXsR+g0Guwe8l5",
	"pVa1xO/wzH0ApQ8cLrfqEdo2D1tv7/5NRzXTWvfWczDQ51UvLRtfFw2XxXufR+BBT/in9RPKt6UbAcgx",
	"hjCKBZ6rYSR1dVwlrb6mimvptR1FTZ4E3qiQyeeMbcSzW1fswhOnLLQX8Wy1FESBQH/9y5//c/rXv/z5",
	"v4ZsbK4WU8oTYt+zeoVuyog7EnejOjtK0IfbXrv/ZbAWOTClqReK3DDW1FNerZ/SeABt9F8quM6DabMT",
	"EIG+y2BkL5KlYjU+rFJNlkOalGS/VutZ1h0p15fIHaXj1zthocyDe1RtxyHshvzJPk5HVpJG7hmIfdMd",
	"acsXCAtA+qApYGWF0dwMTGJ19xcTvKR2PaJAIkqkvkMRhrBrvdQ8WwzoYUTYvSAcxwKkNEFwAR0jHmRF",
	"0IXQ9DOfrY/Bqgz4Dk9stYhHhT/wmdPNM4RiWvJFX5cVtdIHVIfOhdQ/G1n0yHgLoZr3HuTV2zTCLLL1",
	"/u2v2pvjMGsOwOJ112PaOdSms6rX27u+zZp1UFRf3ChS5IwRloxSqBa+y8UNGN3yTdlOY5j2o4xntrmd",
	"h3Oew/qhSltWNjfjlKIPpz+jZuxpOjvqJ/sRTnhn6PnnHPJGBKaZrZKy/ZFXAZbpDKtosR4y5vnWjgHT",
	"eCL2lVDTfGjngY4ZgFwhedd+1qkXGSWhueCpMf0M7hX6CeUsl1C8dbBPGfoVvjAvSn4fcqLfuyE7dKGt",
	"dy2+UAjEHYkAEYksy6ZF4tvDN1+Hh+JFDdqDg+QAxVjhGZaAciYARws8o/CyFTNb+sj8r1Zq+rA/O22Y",
	"tt2pLN549GmkeggyKmfo3iGMuPv2PWvw0zUPG7ZOtXwp4U1OBjFemZqYLfHbv1LOtAgnvjhgdxe1Ugm+",
	"S1qSCEhMBcFo0/UBArK967s2EOXySCNqWu8Cd/zwOxAIa+A6niYlizhOCUMxlosZx+ZJWoHVc9NV7qBK",
	"2O0sJzQmLJmaxtD9WdF32u83mv2pO3Ic/ibYZ/YcPX3EvuRc0QRWDzpA7Jt+teJiR2R5r6tf6V5IdIYi",
	"TvOU7RxUhk/jdeymNCOul5PnAv3CRXxpbh728kcY0qYQyZyYDk1k9vNCmiKZVCizr1NKbGmKbx2gejGW",
	"Fs+Desspl9WwUcbRNVNveLvYfTV5oDVwAEI1Q5OzCeI0fmSd5LIEoP2/gkl7+SiVoOk/TnvTBZGKi9U4",
	"LX7vBj+5OHb4f7M41mw3HSyPyTyKQMp5TmuN+k+plV37CCIcCS4lwpRqDIyroW0Cjy/2RG6WH3jcKR7K",
	"EVTn7yk5gu1e+bMaT0OizaUR1cD5+mRGPIcdM413I0zYMaXI8r15PTd3u/FkncseUJMmHRZKo8PueaTT",
	"bOobKSbG2b5tz4itr32EyFreuia86osVw7qGoeYWdtk15G3SfebWoZbCehuHHp0T2lmp9TiOEW7pfVDt",
	"nuMzsjuoC4l1VUk7b9dJ1Ws+V+7kbCaKSe9VfM1WD58PeIUF2XW7x2Zy232jlekLtbnKpnY8nf07Mk8D",
	"bwieuXq8FiWW1fhvL2VtGdvQQpkFxF2BrtaBwCkgLkhCGMLSPtHkkUR7Sy5uJeIMYbZCCy7VNOPCxKum",
	"yTuYBvpm0H4aq6PcpBxTvDBMc6oIToCpfQn84I86crOPDfX2HOttYufkDlhRoxOAY2L+MqlBWZ0Mlxrs",
	"MlMrv9tsvptgJNsdXgnO9UTpWNK+gKut1havRwanF2VBodbhberQJeEaN0WmuUvpnb5Z7i9hZmrXptPD",
	"kClTC/VI15FrBrpdmuecJfuU3IGtiuuY0HSC3sKqtstaH+jDzcP/BgAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
