// Package oapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapigen

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for ClientSegmentSegment.
const (
	Booked    ClientSegmentSegment = "booked"
	Client    ClientSegmentSegment = "client"
	Consulted ClientSegmentSegment = "consulted"
	Lead      ClientSegmentSegment = "lead"
	Lost      ClientSegmentSegment = "lost"
	Repeat    ClientSegmentSegment = "repeat"
)

// Valid indicates whether the value is a known member of the ClientSegmentSegment enum.
func (e ClientSegmentSegment) Valid() bool {
	switch e {
	case Booked:
		return true
	case Client:
		return true
	case Consulted:
		return true
	case Lead:
		return true
	case Lost:
		return true
	case Repeat:
		return true
	default:
		return false
	}
}

// Defines values for HealthResponseStatus.
const (
	Degraded HealthResponseStatus = "degraded"
	Ok       HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for RateArticleRequestRating.
const (
	Dislike RateArticleRequestRating = "dislike"
	Like    RateArticleRequestRating = "like"
	None    RateArticleRequestRating = "none"
)

// Valid indicates whether the value is a known member of the RateArticleRequestRating enum.
func (e RateArticleRequestRating) Valid() bool {
	switch e {
	case Dislike:
		return true
	case Like:
		return true
	case None:
		return true
	default:
		return false
	}
}

// Defines values for SiteProvider.
const (
	Modx      SiteProvider = "modx"
	Wordpress SiteProvider = "wordpress"
)

// Valid indicates whether the value is a known member of the SiteProvider enum.
func (e SiteProvider) Valid() bool {
	switch e {
	case Modx:
		return true
	case Wordpress:
		return true
	default:
		return false
	}
}

// Defines values for GetLeadStatsParamsGroupBy.
const (
	Day   GetLeadStatsParamsGroupBy = "day"
	Month GetLeadStatsParamsGroupBy = "month"
)

// Valid indicates whether the value is a known member of the GetLeadStatsParamsGroupBy enum.
func (e GetLeadStatsParamsGroupBy) Valid() bool {
	switch e {
	case Day:
		return true
	case Month:
		return true
	default:
		return false
	}
}

// ApiToken defines model for ApiToken.
type ApiToken struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Prefix    string             `json:"prefix"`
}

// ApiTokenCreated defines model for ApiTokenCreated.
type ApiTokenCreated struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Prefix    string             `json:"prefix"`
	Token     string             `json:"token"`
}

// Article defines model for Article.
type Article struct {
	AiScore         *float32            `json:"ai_score,omitempty"`
	CheckResult     *json.RawMessage    `json:"check_result,omitempty"`
	CompetitorData  *json.RawMessage    `json:"competitor_data,omitempty"`
	CreatedAt       time.Time           `json:"created_at"`
	HumanRating     *bool               `json:"human_rating,omitempty"`
	HumanizeCycles  *int                `json:"humanize_cycles,omitempty"`
	Id              int64               `json:"id"`
	ImagesRequested *int                `json:"images_requested,omitempty"`
	ImagesResolved  *int                `json:"images_resolved,omitempty"`
	ImagesSkipped   *int                `json:"images_skipped,omitempty"`
	Keyword         string              `json:"keyword"`
	PublishedAt     *time.Time          `json:"published_at,omitempty"`
	QualityOk       *bool               `json:"quality_ok,omitempty"`
	RequestParams   *json.RawMessage    `json:"request_params,omitempty"`
	Reward          *float32            `json:"reward,omitempty"`
	Site            *string             `json:"site,omitempty"`
	SiteId          *openapi_types.UUID `json:"site_id,omitempty"`
	Status          string              `json:"status"`
	Tokens          *int                `json:"tokens,omitempty"`
	UpdatedAt       time.Time           `json:"updated_at"`
	WpEditUrl       *string             `json:"wp_edit_url,omitempty"`
	WpPostId        *int64              `json:"wp_post_id,omitempty"`
	WpPostUrl       *string             `json:"wp_post_url,omitempty"`
}

// ArticleList defines model for ArticleList.
type ArticleList struct {
	Items []Article `json:"items"`
	Total int64     `json:"total"`
}

// ClientSegment defines model for ClientSegment.
type ClientSegment struct {
	CaseCount    int64                `json:"case_count"`
	CaseFee      float32              `json:"case_fee"`
	CasePaid     float32              `json:"case_paid"`
	ClientId     string               `json:"client_id"`
	LastActivity time.Time            `json:"last_activity"`
	Name         string               `json:"name"`
	Phone        string               `json:"phone"`
	Segment      ClientSegmentSegment `json:"segment"`
	Tags         []string             `json:"tags"`
}

// ClientSegmentSegment defines model for ClientSegment.Segment.
type ClientSegmentSegment string

// CreateApiTokenRequest defines model for CreateApiTokenRequest.
type CreateApiTokenRequest struct {
	Name string `json:"name" validate:"required,min=1,max=100"`
}

// CreateWordpressSiteRequest defines model for CreateWordpressSiteRequest.
type CreateWordpressSiteRequest struct {
	Alias       string                    `json:"alias" validate:"required,min=1,max=100"`
	AppPassword *string                   `json:"appPassword,omitempty" validate:"required"`
	Languages   map[string]LanguageConfig `json:"languages,omitempty"`
	Provider    SiteProvider              `json:"provider" validate:"required,oneof=wordpress modx"`
	Url         string                    `json:"url" validate:"required,url"`
	Username    *string                   `json:"username,omitempty" validate:"required_if=Provider wordpress,omitempty,max=255"`
}

// ErrorResponse RFC 7807 problem details
type ErrorResponse struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     *string `json:"type,omitempty"`
}

// GenerateAccepted defines model for GenerateAccepted.
type GenerateAccepted struct {
	CreatedAt      time.Time           `json:"created_at"`
	Id             int64               `json:"id"`
	Keyword        string              `json:"keyword"`
	Model          *string             `json:"model,omitempty"`
	Provider       *string             `json:"provider,omitempty"`
	Site           *string             `json:"site,omitempty"`
	SiteId         *openapi_types.UUID `json:"site_id,omitempty"`
	Status         string              `json:"status"`
	StatusUrl      *string             `json:"status_url,omitempty"`
	SuggestedTitle *string             `json:"suggested_title,omitempty"`
	TargetKeywords []string            `json:"target_keywords,omitempty"`
}

// GenerateBatchAccepted defines model for GenerateBatchAccepted.
type GenerateBatchAccepted struct {
	ArticleIds []int64 `json:"article_ids"`
	Count      int     `json:"count"`
}

// GenerateBatchRequest defines model for GenerateBatchRequest.
type GenerateBatchRequest struct {
	AiThreshold   *float32           `json:"ai_threshold,omitempty"`
	AutoPublish   *bool              `json:"auto_publish,omitempty"`
	Count         int                `json:"count" validate:"required,min=1,max=100"`
	IncludeImages *bool              `json:"include_images,omitempty"`
	Language      *string            `json:"language,omitempty"`
	MaxCycles     *int               `json:"max_cycles,omitempty"`
	MaxTokens     *int               `json:"max_tokens,omitempty"`
	MaxWords      *int               `json:"max_words,omitempty"`
	MinWords      *int               `json:"min_words,omitempty"`
	Model         *string            `json:"model,omitempty"`
	Provider      *string            `json:"provider,omitempty"`
	SiteId        openapi_types.UUID `json:"site_id" validate:"required"`
}

// GenerateRequest defines model for GenerateRequest.
type GenerateRequest struct {
	AiThreshold             *float32           `json:"ai_threshold,omitempty"`
	AutoPublish             *bool              `json:"auto_publish,omitempty"`
	ExtraRules              *string            `json:"extra_rules,omitempty"`
	IncludeImageAttribution *bool              `json:"include_image_attribution,omitempty"`
	IncludeImages           *bool              `json:"include_images,omitempty"`
	Keyword                 string             `json:"keyword" validate:"required,min=1,max=200"`
	Language                *string            `json:"language,omitempty"`
	MaxCycles               *int               `json:"max_cycles,omitempty"`
	MaxTokens               *int               `json:"max_tokens,omitempty"`
	MaxWords                *int               `json:"max_words,omitempty"`
	MinWords                *int               `json:"min_words,omitempty"`
	Model                   *string            `json:"model,omitempty"`
	Provider                *string            `json:"provider,omitempty"`
	SiteId                  openapi_types.UUID `json:"site_id" validate:"required"`
	SiteTopic               *string            `json:"site_topic,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
	Time   time.Time            `json:"time"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// LanguageConfig Per-language settings for a bilingual site — which MODX context a language publishes into, and which keyword sheet (if any) supplies its generation topics.
type LanguageConfig struct {
	ContextKey            *string `json:"contextKey,omitempty"`
	KeywordsSheet         *string `json:"keywordsSheet,omitempty"`
	KeywordsSpreadsheetId *string `json:"keywordsSpreadsheetId,omitempty"`
}

// LeadStats defines model for LeadStats.
type LeadStats struct {
	ByCategory []LeadStatsCategoryRevenue `json:"by_category"`
	ByCreator  []LeadStatsCreatorRevenue  `json:"by_creator"`
	ByPage     []LeadStatsCount           `json:"by_page"`
	ByStatus   []LeadStatsCount           `json:"by_status"`
	Range      struct {
		From    openapi_types.Date `json:"from"`
		GroupBy string             `json:"group_by"`
		To      openapi_types.Date `json:"to"`
	} `json:"range"`
	Totals struct {
		AvgTicket         float32 `json:"avg_ticket"`
		CaseFeeContracted float32 `json:"case_fee_contracted"`
		CaseOwed          float32 `json:"case_owed"`
		CasePaid          float32 `json:"case_paid"`
		CasesCompleted    int64   `json:"cases_completed"`
		CasesInProgress   int64   `json:"cases_in_progress"`
		Clients           int64   `json:"clients"`
		Consultations     int64   `json:"consultations"`
		Leads             int64   `json:"leads"`
		OrganicSessions   int64   `json:"organic_sessions"`
		RevenueBooked     float32 `json:"revenue_booked"`
		RevenueEarned     float32 `json:"revenue_earned"`
		RevenueLost       float32 `json:"revenue_lost"`
		SiteSessions      int64   `json:"site_sessions"`
	} `json:"totals"`
	Trend []LeadStatsBucket `json:"trend"`
}

// LeadStatsBucket defines model for LeadStatsBucket.
type LeadStatsBucket struct {
	Bucket          string  `json:"bucket"`
	Consultations   int64   `json:"consultations"`
	Leads           int64   `json:"leads"`
	OrganicSessions int64   `json:"organic_sessions"`
	RevenueEarned   float32 `json:"revenue_earned"`
	SiteSessions    int64   `json:"site_sessions"`
}

// LeadStatsCategoryRevenue defines model for LeadStatsCategoryRevenue.
type LeadStatsCategoryRevenue struct {
	Cases      int64   `json:"cases"`
	Contracted float32 `json:"contracted"`
	Key        string  `json:"key"`
	Paid       float32 `json:"paid"`
}

// LeadStatsCount defines model for LeadStatsCount.
type LeadStatsCount struct {
	Count int64  `json:"count"`
	Key   string `json:"key"`
}

// LeadStatsCreatorRevenue defines model for LeadStatsCreatorRevenue.
type LeadStatsCreatorRevenue struct {
	Bookings      int64   `json:"bookings"`
	Key           string  `json:"key"`
	RevenueEarned float32 `json:"revenue_earned"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required,min=1"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Token     string    `json:"token"`
}

// PlaceBacklinksAccepted defines model for PlaceBacklinksAccepted.
type PlaceBacklinksAccepted struct {
	RunId       string `json:"run_id"`
	Sheet       string `json:"sheet"`
	SitesQueued int    `json:"sites_queued"`
}

// PlaceBacklinksRequest defines model for PlaceBacklinksRequest.
type PlaceBacklinksRequest struct {
	// Count Stop after this many SUCCESSFUL placements (failures don't count). Defaults to 3 when omitted.
	Count *int `json:"count,omitempty"`

	// Model Override the default LLM model for this run only. Falls back to LLM_BACKLINK_MODEL (or LLM_MODEL) when empty.
	Model *string `json:"model,omitempty"`

	// Provider Override the default LLM provider for this run only. Falls back to LLM_BACKLINK_PROVIDER (or LLM_PROVIDER) when empty.
	Provider *string `json:"provider,omitempty"`
	Sheet    string  `json:"sheet" validate:"required,min=1"`

	// TargetSiteUrl Public URL of one of the user's wordpress_sites; the backend rejects URLs not present in that table.
	TargetSiteUrl string `json:"target_site_url" validate:"required,url"`
}

// Placement defines model for Placement.
type Placement struct {
	Anchor    *string   `json:"anchor,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	DonorUrl  string    `json:"donor_url"`
	EditUrl   *string   `json:"edit_url,omitempty"`
	Id        int64     `json:"id"`
	Ok        bool      `json:"ok"`
	Outcome   *string   `json:"outcome,omitempty"`
	PostUrl   *string   `json:"post_url,omitempty"`
	Status    string    `json:"status"`
	TargetUrl string    `json:"target_url"`
}

// PlacementList defines model for PlacementList.
type PlacementList struct {
	Items []Placement `json:"items"`
	Total int         `json:"total"`
}

// RateArticleRequest defines model for RateArticleRequest.
type RateArticleRequest struct {
	Rating RateArticleRequestRating `json:"rating"`
}

// RateArticleRequestRating defines model for RateArticleRequest.Rating.
type RateArticleRequestRating string

// ScrapeEmailsAccepted defines model for ScrapeEmailsAccepted.
type ScrapeEmailsAccepted struct {
	JobId       string `json:"job_id"`
	Sheet       string `json:"sheet"`
	SitesQueued int    `json:"sites_queued"`
}

// ScrapeEmailsRequest defines model for ScrapeEmailsRequest.
type ScrapeEmailsRequest struct {
	Sheet string `json:"sheet" validate:"required,min=1"`
}

// ScrapeJob defines model for ScrapeJob.
type ScrapeJob struct {
	Id        string `json:"id"`
	Processed int    `json:"processed"`
	Sheet     string `json:"sheet"`
	State     string `json:"state"`
	Total     int    `json:"total"`
}

// SiteProvider defines model for SiteProvider.
type SiteProvider string

// UpdateWordpressSiteRequest defines model for UpdateWordpressSiteRequest.
type UpdateWordpressSiteRequest struct {
	Alias       *string                   `json:"alias,omitempty" validate:"omitempty,min=1,max=100"`
	AppPassword *string                   `json:"appPassword,omitempty"`
	Enabled     *bool                     `json:"enabled,omitempty"`
	Languages   map[string]LanguageConfig `json:"languages,omitempty"`
	Url         *string                   `json:"url,omitempty" validate:"omitempty,url"`
	Username    *string                   `json:"username,omitempty" validate:"omitempty,max=255"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time          `json:"createdAt"`
	Email     string             `json:"email"`
	Id        openapi_types.UUID `json:"id"`
}

// WordpressSite defines model for WordpressSite.
type WordpressSite struct {
	Alias     string                    `json:"alias"`
	CreatedAt time.Time                 `json:"createdAt"`
	Enabled   bool                      `json:"enabled"`
	Id        openapi_types.UUID        `json:"id"`
	Languages map[string]LanguageConfig `json:"languages,omitempty"`
	Provider  SiteProvider              `json:"provider"`
	UpdatedAt time.Time                 `json:"updatedAt"`
	Url       string                    `json:"url"`
	Username  string                    `json:"username"`
}

// BadRequest RFC 7807 problem details
type BadRequest = ErrorResponse

// Conflict RFC 7807 problem details
type Conflict = ErrorResponse

// NotFound RFC 7807 problem details
type NotFound = ErrorResponse

// Unauthorized RFC 7807 problem details
type Unauthorized = ErrorResponse

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListArticlesParams defines parameters for ListArticles.
type ListArticlesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetLeadStatsParams defines parameters for GetLeadStats.
type GetLeadStatsParams struct {
	From    openapi_types.Date         `form:"from" json:"from"`
	To      openapi_types.Date         `form:"to" json:"to"`
	GroupBy *GetLeadStatsParamsGroupBy `form:"group_by,omitempty" json:"group_by,omitempty"`
}

// GetLeadStatsParamsGroupBy defines parameters for GetLeadStats.
type GetLeadStatsParamsGroupBy string

// ListPlacementsParams defines parameters for ListPlacements.
type ListPlacementsParams struct {
	RunId string `form:"run_id" json:"run_id"`
}

// ListPlacementHistoryParams defines parameters for ListPlacementHistory.
type ListPlacementHistoryParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateApiTokenJSONRequestBody defines body for CreateApiToken for application/json ContentType.
type CreateApiTokenJSONRequestBody = CreateApiTokenRequest

// RateArticleJSONRequestBody defines body for RateArticle for application/json ContentType.
type RateArticleJSONRequestBody = RateArticleRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ScrapeEmailsJSONRequestBody defines body for ScrapeEmails for application/json ContentType.
type ScrapeEmailsJSONRequestBody = ScrapeEmailsRequest

// GenerateArticleJSONRequestBody defines body for GenerateArticle for application/json ContentType.
type GenerateArticleJSONRequestBody = GenerateRequest

// GenerateBatchJSONRequestBody defines body for GenerateBatch for application/json ContentType.
type GenerateBatchJSONRequestBody = GenerateBatchRequest

// PlaceBacklinksJSONRequestBody defines body for PlaceBacklinks for application/json ContentType.
type PlaceBacklinksJSONRequestBody = PlaceBacklinksRequest

// CreateWordpressSiteJSONRequestBody defines body for CreateWordpressSite for application/json ContentType.
type CreateWordpressSiteJSONRequestBody = CreateWordpressSiteRequest

// UpdateWordpressSiteJSONRequestBody defines body for UpdateWordpressSite for application/json ContentType.
type UpdateWordpressSiteJSONRequestBody = UpdateWordpressSiteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List your API tokens (metadata only)
	// (GET /api-tokens)
	ListApiTokens(w http.ResponseWriter, r *http.Request)
	// Create an API token (the secret is returned only once)
	// (POST /api-tokens)
	CreateApiToken(w http.ResponseWriter, r *http.Request)
	// Revoke an API token
	// (DELETE /api-tokens/{id})
	DeleteApiToken(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List articles (paginated, newest first)
	// (GET /articles)
	ListArticles(w http.ResponseWriter, r *http.Request, params ListArticlesParams)
	// Get an article
	// (GET /articles/{id})
	GetArticle(w http.ResponseWriter, r *http.Request, id int64)
	// Publish a draft article
	// (POST /articles/{id}/publish)
	PublishArticle(w http.ResponseWriter, r *http.Request, id int64)
	// Rate an article (copywriter 👍/👎)
	// (POST /articles/{id}/rating)
	RateArticle(w http.ResponseWriter, r *http.Request, id int64)
	// Authenticate and receive a JWT
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Every client with their derived funnel segment and tags — no date range, this is a snapshot of all-time activity, not a period aggregate
	// (GET /clients)
	ListClientSegments(w http.ResponseWriter, r *http.Request)
	// Crawl the sites listed in a sheet and scrape their email addresses
	// (POST /emailscrape)
	ScrapeEmails(w http.ResponseWriter, r *http.Request)
	// Get the progress and state of a scrape job
	// (GET /emailscrape/jobs/{id})
	GetScrapeJob(w http.ResponseWriter, r *http.Request, id string)
	// Request cancellation of a running scrape job
	// (POST /emailscrape/jobs/{id}/cancel)
	CancelScrapeJob(w http.ResponseWriter, r *http.Request, id string)
	// Queue an article for generation
	// (POST /generate)
	GenerateArticle(w http.ResponseWriter, r *http.Request)
	// Queue a batch from the next N unused sheet topics
	// (POST /generate/batch)
	GenerateBatch(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// Aggregate lead/consultation stats over a date range, for the admin dashboard
	// (GET /leads/stats)
	GetLeadStats(w http.ResponseWriter, r *http.Request, params GetLeadStatsParams)
	// Place a backlink to one of our WordPress sites in each suitable donor's latest post
	// (POST /linkbuilding/place-backlinks)
	PlaceBacklinks(w http.ResponseWriter, r *http.Request)
	// Per-donor results of a placement run
	// (GET /linkbuilding/placements)
	ListPlacements(w http.ResponseWriter, r *http.Request, params ListPlacementsParams)
	// Successful placements across all runs (paginated, newest first)
	// (GET /linkbuilding/placements/history)
	ListPlacementHistory(w http.ResponseWriter, r *http.Request, params ListPlacementHistoryParams)
	// Request cancellation of a running placement
	// (POST /linkbuilding/placements/{run_id}/cancel)
	CancelPlacement(w http.ResponseWriter, r *http.Request, runId string)
	// List users
	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request)
	// List WordPress sites
	// (GET /wordpress-sites)
	ListWordpressSites(w http.ResponseWriter, r *http.Request)
	// Add a WordPress site
	// (POST /wordpress-sites)
	CreateWordpressSite(w http.ResponseWriter, r *http.Request)
	// Soft-delete a WordPress site
	// (DELETE /wordpress-sites/{id})
	DeleteWordpressSite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get a WordPress site
	// (GET /wordpress-sites/{id})
	GetWordpressSite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update a WordPress site
	// (PATCH /wordpress-sites/{id})
	UpdateWordpressSite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List your API tokens (metadata only)
// (GET /api-tokens)
func (_ Unimplemented) ListApiTokens(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an API token (the secret is returned only once)
// (POST /api-tokens)
func (_ Unimplemented) CreateApiToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke an API token
// (DELETE /api-tokens/{id})
func (_ Unimplemented) DeleteApiToken(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List articles (paginated, newest first)
// (GET /articles)
func (_ Unimplemented) ListArticles(w http.ResponseWriter, r *http.Request, params ListArticlesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get an article
// (GET /articles/{id})
func (_ Unimplemented) GetArticle(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Publish a draft article
// (POST /articles/{id}/publish)
func (_ Unimplemented) PublishArticle(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rate an article (copywriter 👍/👎)
// (POST /articles/{id}/rating)
func (_ Unimplemented) RateArticle(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Authenticate and receive a JWT
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Every client with their derived funnel segment and tags — no date range, this is a snapshot of all-time activity, not a period aggregate
// (GET /clients)
func (_ Unimplemented) ListClientSegments(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Crawl the sites listed in a sheet and scrape their email addresses
// (POST /emailscrape)
func (_ Unimplemented) ScrapeEmails(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the progress and state of a scrape job
// (GET /emailscrape/jobs/{id})
func (_ Unimplemented) GetScrapeJob(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request cancellation of a running scrape job
// (POST /emailscrape/jobs/{id}/cancel)
func (_ Unimplemented) CancelScrapeJob(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Queue an article for generation
// (POST /generate)
func (_ Unimplemented) GenerateArticle(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Queue a batch from the next N unused sheet topics
// (POST /generate/batch)
func (_ Unimplemented) GenerateBatch(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Aggregate lead/consultation stats over a date range, for the admin dashboard
// (GET /leads/stats)
func (_ Unimplemented) GetLeadStats(w http.ResponseWriter, r *http.Request, params GetLeadStatsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Place a backlink to one of our WordPress sites in each suitable donor's latest post
// (POST /linkbuilding/place-backlinks)
func (_ Unimplemented) PlaceBacklinks(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Per-donor results of a placement run
// (GET /linkbuilding/placements)
func (_ Unimplemented) ListPlacements(w http.ResponseWriter, r *http.Request, params ListPlacementsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Successful placements across all runs (paginated, newest first)
// (GET /linkbuilding/placements/history)
func (_ Unimplemented) ListPlacementHistory(w http.ResponseWriter, r *http.Request, params ListPlacementHistoryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request cancellation of a running placement
// (POST /linkbuilding/placements/{run_id}/cancel)
func (_ Unimplemented) CancelPlacement(w http.ResponseWriter, r *http.Request, runId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List users
// (GET /users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List WordPress sites
// (GET /wordpress-sites)
func (_ Unimplemented) ListWordpressSites(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a WordPress site
// (POST /wordpress-sites)
func (_ Unimplemented) CreateWordpressSite(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Soft-delete a WordPress site
// (DELETE /wordpress-sites/{id})
func (_ Unimplemented) DeleteWordpressSite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a WordPress site
// (GET /wordpress-sites/{id})
func (_ Unimplemented) GetWordpressSite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a WordPress site
// (PATCH /wordpress-sites/{id})
func (_ Unimplemented) UpdateWordpressSite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListApiTokens operation middleware
func (siw *ServerInterfaceWrapper) ListApiTokens(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApiTokens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateApiToken operation middleware
func (siw *ServerInterfaceWrapper) CreateApiToken(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateApiToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiToken operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiToken(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiToken(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListArticles operation middleware
func (siw *ServerInterfaceWrapper) ListArticles(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListArticlesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListArticles(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArticle operation middleware
func (siw *ServerInterfaceWrapper) GetArticle(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArticle(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PublishArticle operation middleware
func (siw *ServerInterfaceWrapper) PublishArticle(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PublishArticle(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RateArticle operation middleware
func (siw *ServerInterfaceWrapper) RateArticle(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RateArticle(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListClientSegments operation middleware
func (siw *ServerInterfaceWrapper) ListClientSegments(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListClientSegments(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ScrapeEmails operation middleware
func (siw *ServerInterfaceWrapper) ScrapeEmails(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ScrapeEmails(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetScrapeJob operation middleware
func (siw *ServerInterfaceWrapper) GetScrapeJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetScrapeJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelScrapeJob operation middleware
func (siw *ServerInterfaceWrapper) CancelScrapeJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelScrapeJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateArticle operation middleware
func (siw *ServerInterfaceWrapper) GenerateArticle(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateArticle(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateBatch operation middleware
func (siw *ServerInterfaceWrapper) GenerateBatch(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateBatch(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLeadStats operation middleware
func (siw *ServerInterfaceWrapper) GetLeadStats(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLeadStatsParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "group_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "group_by", r.URL.Query(), &params.GroupBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "group_by"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "group_by", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLeadStats(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlaceBacklinks operation middleware
func (siw *ServerInterfaceWrapper) PlaceBacklinks(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlaceBacklinks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPlacements operation middleware
func (siw *ServerInterfaceWrapper) ListPlacements(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPlacementsParams

	// ------------- Required query parameter "run_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "run_id", r.URL.Query(), &params.RunId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "run_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "run_id", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPlacements(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPlacementHistory operation middleware
func (siw *ServerInterfaceWrapper) ListPlacementHistory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPlacementHistoryParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPlacementHistory(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelPlacement operation middleware
func (siw *ServerInterfaceWrapper) CancelPlacement(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "run_id" -------------
	var runId string

	err = runtime.BindStyledParameterWithOptions("simple", "run_id", chi.URLParam(r, "run_id"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "run_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelPlacement(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWordpressSites operation middleware
func (siw *ServerInterfaceWrapper) ListWordpressSites(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWordpressSites(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWordpressSite operation middleware
func (siw *ServerInterfaceWrapper) CreateWordpressSite(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWordpressSite(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteWordpressSite operation middleware
func (siw *ServerInterfaceWrapper) DeleteWordpressSite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteWordpressSite(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWordpressSite operation middleware
func (siw *ServerInterfaceWrapper) GetWordpressSite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWordpressSite(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateWordpressSite operation middleware
func (siw *ServerInterfaceWrapper) UpdateWordpressSite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateWordpressSite(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api-tokens", wrapper.ListApiTokens)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api-tokens", wrapper.CreateApiToken)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api-tokens/{id}", wrapper.DeleteApiToken)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/articles", wrapper.ListArticles)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/articles/{id}", wrapper.GetArticle)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/articles/{id}/publish", wrapper.PublishArticle)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/articles/{id}/rating", wrapper.RateArticle)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/clients", wrapper.ListClientSegments)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/emailscrape", wrapper.ScrapeEmails)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/emailscrape/jobs/{id}", wrapper.GetScrapeJob)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/emailscrape/jobs/{id}/cancel", wrapper.CancelScrapeJob)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/generate", wrapper.GenerateArticle)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/generate/batch", wrapper.GenerateBatch)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/leads/stats", wrapper.GetLeadStats)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/linkbuilding/place-backlinks", wrapper.PlaceBacklinks)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/linkbuilding/placements", wrapper.ListPlacements)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/linkbuilding/placements/history", wrapper.ListPlacementHistory)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/linkbuilding/placements/{run_id}/cancel", wrapper.CancelPlacement)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/wordpress-sites", wrapper.ListWordpressSites)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/wordpress-sites", wrapper.CreateWordpressSite)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/wordpress-sites/{id}", wrapper.DeleteWordpressSite)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/wordpress-sites/{id}", wrapper.GetWordpressSite)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/wordpress-sites/{id}", wrapper.UpdateWordpressSite)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7FzvbiQ3cn8VohPAWmSkkXft3EUHf9DuateytV5F8sYJHKHB6a6Z4aqHbJNsSeOFgEsCHBAgf3BBkK/3",
	"ChcgBoIczs+gfYV7gnuEgEX2f3ZPj6TROkA+7UpNFotVvypWFYt6F0RikQoOXKtg710gQaWCK8AfntL4",
	"BL7LQGnzUyS4Bo7/pWmasIhqJvg4lWKSwOLP3irBzTcVzWFBzf/+VMI02Av+ZFwuMbZf1fhASiFP3GLB",
	"9fX1KIhBRZKlhmiwFxzyC5qwmEjHwPUoeCb4NGHRB2AmX5lcMj0ncMWUZnxGJCiRyQgMc18J/UJkPH54",
	"5k4cF4QLTabIw/UoeMNppudCsu/hA/D0iillJCQkYU6RE6ASJNHiHHhgZjhiZq39lH2Nv997F6RSpCA1",
	"sxCMJFAN8T4yPhVyQXWwF8RUw7ZmCwhGgV6mEOwFSkvGZ2bnLK6NzTIW+4ZxugAzsPUhlTBlV55P16PA",
	"oJFJI9FvAySLVIo5owq/Z8WaYvIWIkRwvs9ndtRPe7ujQOc6uYUg7NyVApGaRQm0BUFZqCIh8QvPkoRO",
	"zCgtMyio8GwxAWmoRHOIzkMJKkt0zwS37Ci42p6JbfdLA/ydE3r5CpSiMzRlA3jQTAsZxlTT+6BohRDS",
	"NfQ6zxaUh5IaT9PDwkSIBCgvZrDvIYyWUWLF2DGJcQ0zK7sGfBjXf/5J4B24oDNQofPHFrw9o5RILlYM",
	"UucsTbvGnMPyUsjYD9lskjA17xdox9ZLKt9lNGF6GYrzYeJ1Ow9TKulC3QMqJFxSu8OVCFdM+63XfAj9",
	"LmClAJSmOlPdlj8QQVkarw3uyzSEmOkwk4l3/cs0TIXS4WB05hP8BH0OKwdYIYeamda21eO5jpgNjure",
	"i2lY1P/Td5rmTvC6WIZKSZdWD5omg0TQ3CIunBPwbeBZwoDrU5gtXFjQOImogjASGdcDNYATplCFacVD",
	"m48pZbH/K7ISMr+1J1TpkEaaXTC9HA6x7gNvLniHMZXCAJ4tjBwToAYiEyHOwfwnEtycMvb/yHZgBJ8C",
	"YiYRqoqWij3RWR0P7RE1zTe0WQqoPGhxFyXPbo2muEZVRVaUVFWJFx1oCnm8UskC6ijxC9l4PkFTth2J",
	"GGbAt+FKS7qdCwHjQWocWrHJ0YLxzz4eLejVZx/v7tqIsioAXKebz2+EjFMJSp0yDZ3M0oRRtRFuRyam",
	"PqZK+Y+s9VdAmgnls8yclMh8HDMTXNPkuLapPsdy5AiY9IVVUVbKL5XigsUgrXyS19Ng79t+okbEx/ms",
	"67NbSE9wENPPLnOdkYWIr3DDXud9iwUMHaSnQN4XQkM2/SzfNil4H4mFMelULxENjz/9tI1dC7uKqO1G",
	"fWiu51V775qZ3otn5Gc/3/0ZcVkbiUFTljjiFVDY33v9DONKUx51OMBmRFDx75rpBHpc16pD184v1vBt",
	"/yVwkMbtRBGkffnRWrHG4BiiL+RciBiSjvyptCBvePaQcZv91BlWqWw2w+A97NEmlTPQoRPGXU6tAWFW",
	"HwqeUh3Nu6FAbdQUsgaPAxTdjLKKMGdFUJWfotWlV+6g+zhioZ5LUHOR+MMimmkRulynMqCSknQxfi9H",
	"GuNRksUQ2mxtWI6UH1l+G6JXldS0rRbzvUw8/N8LTHo+M977+fYWHA6psdzqkO8AWL5oH7g2iStkPZRZ",
	"XVXVQ6QCjZBqLdkks4fUEJTcBlmdzvlOWH/ssP7/uF03OEX6WqQsWn30V86AHmB/DjTR82r0U8d1eezl",
	"yZk4D0ZBDDNJY4j9eRez0d+QSKHBdHFc4Wgfw43wuhWuHYPczoFFFGjN+EyRqZCEkglLmPmSECMS8odf",
	"/ju5nLNoTl69fv7XBIv1V5pQUszPa16KMK7FiFAeuxlOukTNATTZYlNC+fIRUVmaJsyM14rMrNNgghPU",
	"mdr5W96KGt2qX8LSi6g8Ijg16/SPSCXQGPk5jP3waAsTaHyqqb2FqvM1WYYR1TATcjm4plKQe+ZmnsAF",
	"8MxbZDH0TUgi5C3I24n91FPnWdYkjYeBn2JpC/dEU1I+89jcVIpFy358QfZMiiwNJ8uOauIAGg3zw5Vx",
	"aoW4zwqxwuVBDb2YhZpF5zWsNipSU4DQoF7SqF7RbowTl31fu+taVIEKjT4ScPQHFtJUyHiYSjEzSebQ",
	"eVgkGjzaFrLQJwydkxirHjhWyBnlLAoVKLXGEtIaUugKbj6p5kOASr5iCNbjfAPwHFqLtQY8rShKoTcF",
	"2tpJi+8Gl6MqYH0gaMPJD+IqKKvwbW7aoyKveUmwl9rrOZqnGW5kVYpo3U5hxPlypdeseeeq6xvVjoWz",
	"vhPF8dI+V7KGdyg91k/cOnqgf2dkO6mMSoh3ALvA8a1w1XlAe28i1vBqfc78vCO06fDg7TA2t8KgtpQj",
	"0L/NPFVvxlzDb1j83PuZRLL9DNUjl7Z1CHFuAtY7MTcAsl7+i8VbBLx7EjPWfUcBC28t9BZ5o6V0jYC5",
	"v1q/TUfbxQC7WmWtnq135UxwlTIJap1+koFNH3l/R7mCj73jhEbwlEbnCePnqruYJzPedf2nOtMN43dU",
	"+F0Gmb+JoJnQIaHGtFG+9GruOwFW2HA9/TvVIiV0qkESPWeKLChfktM3z54dnJ6+eHNEUkN9YY5PsjWl",
	"LMkkKBIL/pEmSPHRDnkOU5olWhEtyBNyOQdOxIJpDfEOip6aUCDYezLqqxvUuXp9AVKyGIieA4ktfXJ0",
	"9IrgeMxOkVuZcSJ4stwhL2iSKDKh0blh4+joVfh0/9mXR4dffRm+ev384IhsCYm/xp8eWTbxTmTHh69q",
	"1WIga/mUNbk7Pnn9V4fPD04KBvNfNHksBBlECc1ir1kUMCwHf3Pw9PTw64PTeyipFD6gqL/joerq+I2y",
	"QjZJWETenBwRMSWCg/nHiCxTID9S5eUU0lC/wG9GQMBjIsGAW5nZChsGzUjgmjBO9JxqoukkgbpQ5lqn",
	"am88ThO6TLNEwY6GaB6MKoUlye5DCPbersNsm3LpNFh/PwPl0Vz4S2W3uVSKBRey856lt7dl8H2UbUxq",
	"l0JFpiPR1dzQ3QTT3/BjpTu8faYUQG3yyBblht71FAq7jz6aUvt9nTR3bpw5oRpcy07nkVC27RWNJOzc",
	"AClmyv2PCw6emmUrQUJCPj5OI0lTODBRQs/J+lZMPtTJ6pZexXunED0u9/nrr16f3KvD9W6lm+UvxMQD",
	"07irPh+BUl0djj3i17Tj2ngwijEvy9WiXcENJ1f58u6z2t9RAXBxrAQYW1x56+1vsGnugdpxKr0X6/Xj",
	"GA/NzTkX+x3sQzTe3LHXpdz7fTa7dHSztJh/oyw27ty83pGbDW1r96E+T5v6G89rEB2MzevRrTbZh7WB",
	"7fsP3Qs2vAOs6JRdRyQO/b0BZC+mvarv6LSq0CmVUdVkdQttsGBjaJRJppenRgKuPILPWfYzPS9/epFv",
	"54tvvg7cAxdUN34tN2gCamtZjE9FO8LfPySnB6+Je7JTvbxLE6qN0DCzsi08wTM77EUiLsn+8WEwCi5A",
	"Kktpd+fjnV2MGVPgNGXBXvBkZ3fnCZYV9Bx3Mjauoby/ntlDyeAK1zyMg73AhGd5M6gtylSeiT3e3e15",
	"YdR+WTSsKTp/EtQuIbdeG/2NyCTBllcgbiNVrWFLY1Vf355dn40ClS0WVC7d7sjSENk/PnQUyNYCNI2p",
	"pphoPsobbPe+DcwgJ4kzF3K3JVZvoA2K5wNPRbxcS1p9QvJ36TaCGi0zuG6p7ON7Y6L5qMn3fs5+wmtu",
	"RS9sho9yJlxcjgjTJKL8I00mQCRoyeACYpJQbR3MJxZgPiaKXY0rjxXXUr7ljVBeKp9sGf4URBI0Ycqw",
	"lEkOMSKBCB5BJxyuR1V7Gr9j8bW17wTsOVNHyXP8fQ0lNS194mkChQu8UEK5fLJaLsXDxLWkYlepSaXH",
	"AqikC9AgFdJlhk3jXvJu9T3rnuuQHFXgteqYP0Ox2pxrhZPKB/m5+i4DuSzZStiC6aDKiSs7BXuPP/Xd",
	"lPjJiOlUQQedXQ+Zszs60AGPSTCf9ljiPknpDCtGuThHhMMlKE2mTK5rO+g4c0JkK6Uzxo2h12nWjCXX",
	"jzMV92NhKF7FvoRcr8HmJeeVWvlCZ4M29xK0MThabNUjtPs0ts4LwbOWasaVdsGHYKDrVD22bHxYNBzn",
	"zw9vgQcz4S9WTyieuq8FIMcYoSSWdKr7kdTWcVm0+pAqrpTXNhQ1eQp4g0Im32FsI57NHsUuPHHKIluR",
	"SJeXkmmQ5I+/+fU/j//4m1//S5+PzfR8nIgZs8/rvULHa8QNibt2OztI0Lv3vXb3HyowIgeuDfVckWvG",
	"mmbKx6un1P4eA+q/UHCVB+zrlBCByWUosYlkoViDD6vUSrNXZyxUe+H5MFlb/VHpgNTNTlD2D2u4t4wo",
	"A9zzWnZycAFySaxgLD09ByZJDJKZdGKacQ5JaxFMSrggsZE+9iON7B0jU4QSxWmq5kJjxJQkWNAg+evK",
	"Ed6gUZKCZCImdDaTMHO1Vqcytz+nNaxNKSwkd9titTa+IZP0ld8HWebjjbBQ3F54AGLHEeqG/ML+hRNi",
	"JYlKTEFuYxO1vXQiVAIx7lEDL+6FMZ/Dcvjm00l6mdj1mAZFEqZM5su4ARN2aBueLQYcQHEvhMaxBGV7",
	"i3L0oHiIFUEbQuO3YrI6ci7vLTboZ8tFPCr8Qkycbh4ggDaSz3smrai1MWxjvrnU36IsOmR8DwG2N3v1",
	"6m0cUR7ZLo37X7WzMoVr9sDicTvOsXMSW4Qs/wTIpmsQuA6JqoujImXGOeOzQQo1wncV1B6nWzw93Wjk",
	"2Xy79cA+t/W+1mOsL8tic+lzU5Ek5OXB16SeMWA/TtWybxE6bQw9f5lBVoubDbNlKb07Xs7BMp5QHc1X",
	"QwZfeW4YMLWXpB8INfX3uB7o4ADirv83fc469RJUEplKsUDXz+FKk69IxjMF+ZMo++KpW+FzfHj2fd8h",
	"+rkbssEjtPH8zRcKgbxgEZjA1LKMjS2f7j75MDzkD+/IFuzMdkz8TCdUAcm4BBrN6SSBR41Mx9In+Pe6",
	"Kvqwv3bawLbzscqfgnVppHwvNqjS654TDahYdL1O8tPF90n3TrV48OQtKQcxXeJNpm3MsD8tBDciHPni",
	"gM2l14USfKl1ng7ZGEy57k2XZG3cQRTLE4OocfUVg+NHXIAktJb45SzSeME4iamaTwTFl6s5Vo/wVYSD",
	"KuPnk4wlMeOzMbbzbk/ybuHuc6PeVbyhg8PfuvzAJ0dH97evpJq37lWDDpDb2GWYJ3ZMFXldNaX7SJFD",
	"EokkW/CNgwr5xFPHbsow4jpwRSbJN0LGx5h52OSPcWJcIVEZw75agvv5SOHVptIktS+/CmwZik8doDox",
	"tlhZ+Dkuhw1yjq4Ffs3sYvPVpJ6Gzh4IVRxNxkdEJPEtb7eOCwDaPy2pbPJRKMHQv532xnOmtHvOvFqL",
	"n7vBd77S3P2/eaVZbxLuvdRUWRSBUtMsqTyvuMsN56mPIKGRFEoRmiQGA8NuPteBxztrkevVB25nxX01",
	"gtL+7lIjuN+UP63w1CfaTKGoeuzrDY54CD+G7ZIDXNh+khDL9/q38JnbjeeuoOjcxTJpv1BqfZEPI516",
	"K+ZAMXHBt21TTWzP2luIrHFaV4RXfrFiWNXmVd/CJnu9vK3VD9zw1VBYZ7vXrWtCG7sg349jQht671W7",
	"x3wG9nS1IbHqLtnO23RR9VRMtbOc9UQx6kzFV2x19+GAl3uQTTfprCe3zbfHYTevrVXWteN5j7Eh99Tz",
	"8uOB7/xXosSyGv/0StaWsTU9FC4gL3J0NQyCLoAIyWaME6rsw1oRKbJ1KeS5IoITypdkLpQep0JivIqt",
	"+cE4MJlB80GziXJnxZj8XegiSzSjM+B6W4HY+bmJ3OwTUbM9x3qT2BG7AJ7f0UmgMcOfsDSoSstwpcE2",
	"M5WmCVvNdxNQsu3hpeBcJ5uJJe27xcpqTfF6ZHDwurhQqPTl4z10QbjCTV5pblN6bjLL7UuY4N019ucg",
	"maK0UI10Hbl6oNumeST4bDvBbocU5LaJCbF/9xyWlV1WunfbJGzDAsFKLjZRdLRPbN38ePOf739589v3",
	"/3jzw83vb/775gfyh1/9G7n5n5sfb37//u/e/8PN797/0/u/v/nt+1+9/4/3/2o//tfNDze/u/nxUclM",
	"3iBxfXb9vwEAAP//",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
