// Package oapigen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.7.0 DO NOT EDIT.
package oapigen

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"errors"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/go-chi/chi/v5"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

const (
	BearerAuthScopes bearerAuthContextKey = "bearerAuth.Scopes"
)

// Defines values for HealthResponseStatus.
const (
	Degraded HealthResponseStatus = "degraded"
	Ok       HealthResponseStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthResponseStatus enum.
func (e HealthResponseStatus) Valid() bool {
	switch e {
	case Degraded:
		return true
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for RateArticleRequestRating.
const (
	Dislike RateArticleRequestRating = "dislike"
	Like    RateArticleRequestRating = "like"
	None    RateArticleRequestRating = "none"
)

// Valid indicates whether the value is a known member of the RateArticleRequestRating enum.
func (e RateArticleRequestRating) Valid() bool {
	switch e {
	case Dislike:
		return true
	case Like:
		return true
	case None:
		return true
	default:
		return false
	}
}

// Defines values for SiteProvider.
const (
	Modx      SiteProvider = "modx"
	Wordpress SiteProvider = "wordpress"
)

// Valid indicates whether the value is a known member of the SiteProvider enum.
func (e SiteProvider) Valid() bool {
	switch e {
	case Modx:
		return true
	case Wordpress:
		return true
	default:
		return false
	}
}

// Defines values for GetLeadStatsParamsGroupBy.
const (
	Day   GetLeadStatsParamsGroupBy = "day"
	Month GetLeadStatsParamsGroupBy = "month"
)

// Valid indicates whether the value is a known member of the GetLeadStatsParamsGroupBy enum.
func (e GetLeadStatsParamsGroupBy) Valid() bool {
	switch e {
	case Day:
		return true
	case Month:
		return true
	default:
		return false
	}
}

// ApiToken defines model for ApiToken.
type ApiToken struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Prefix    string             `json:"prefix"`
}

// ApiTokenCreated defines model for ApiTokenCreated.
type ApiTokenCreated struct {
	CreatedAt time.Time          `json:"createdAt"`
	Id        openapi_types.UUID `json:"id"`
	Name      string             `json:"name"`
	Prefix    string             `json:"prefix"`
	Token     string             `json:"token"`
}

// Article defines model for Article.
type Article struct {
	AiScore         *float32            `json:"ai_score,omitempty"`
	CheckResult     *json.RawMessage    `json:"check_result,omitempty"`
	CompetitorData  *json.RawMessage    `json:"competitor_data,omitempty"`
	CreatedAt       time.Time           `json:"created_at"`
	HumanRating     *bool               `json:"human_rating,omitempty"`
	HumanizeCycles  *int                `json:"humanize_cycles,omitempty"`
	Id              int64               `json:"id"`
	ImagesRequested *int                `json:"images_requested,omitempty"`
	ImagesResolved  *int                `json:"images_resolved,omitempty"`
	ImagesSkipped   *int                `json:"images_skipped,omitempty"`
	Keyword         string              `json:"keyword"`
	PublishedAt     *time.Time          `json:"published_at,omitempty"`
	QualityOk       *bool               `json:"quality_ok,omitempty"`
	RequestParams   *json.RawMessage    `json:"request_params,omitempty"`
	Reward          *float32            `json:"reward,omitempty"`
	Site            *string             `json:"site,omitempty"`
	SiteId          *openapi_types.UUID `json:"site_id,omitempty"`
	Status          string              `json:"status"`
	Tokens          *int                `json:"tokens,omitempty"`
	UpdatedAt       time.Time           `json:"updated_at"`
	WpEditUrl       *string             `json:"wp_edit_url,omitempty"`
	WpPostId        *int64              `json:"wp_post_id,omitempty"`
	WpPostUrl       *string             `json:"wp_post_url,omitempty"`
}

// ArticleList defines model for ArticleList.
type ArticleList struct {
	Items []Article `json:"items"`
	Total int64     `json:"total"`
}

// CreateApiTokenRequest defines model for CreateApiTokenRequest.
type CreateApiTokenRequest struct {
	Name string `json:"name" validate:"required,min=1,max=100"`
}

// CreateWordpressSiteRequest defines model for CreateWordpressSiteRequest.
type CreateWordpressSiteRequest struct {
	Alias       string                    `json:"alias" validate:"required,min=1,max=100"`
	AppPassword *string                   `json:"appPassword,omitempty" validate:"required"`
	Languages   map[string]LanguageConfig `json:"languages,omitempty"`
	Provider    SiteProvider              `json:"provider" validate:"required,oneof=wordpress modx"`
	Url         string                    `json:"url" validate:"required,url"`
	Username    *string                   `json:"username,omitempty" validate:"required_if=Provider wordpress,omitempty,max=255"`
}

// ErrorResponse RFC 7807 problem details
type ErrorResponse struct {
	Detail   *string `json:"detail,omitempty"`
	Instance *string `json:"instance,omitempty"`
	Status   int     `json:"status"`
	Title    string  `json:"title"`
	Type     *string `json:"type,omitempty"`
}

// GenerateAccepted defines model for GenerateAccepted.
type GenerateAccepted struct {
	CreatedAt      time.Time           `json:"created_at"`
	Id             int64               `json:"id"`
	Keyword        string              `json:"keyword"`
	Model          *string             `json:"model,omitempty"`
	Provider       *string             `json:"provider,omitempty"`
	Site           *string             `json:"site,omitempty"`
	SiteId         *openapi_types.UUID `json:"site_id,omitempty"`
	Status         string              `json:"status"`
	StatusUrl      *string             `json:"status_url,omitempty"`
	SuggestedTitle *string             `json:"suggested_title,omitempty"`
	TargetKeywords []string            `json:"target_keywords,omitempty"`
}

// GenerateBatchAccepted defines model for GenerateBatchAccepted.
type GenerateBatchAccepted struct {
	ArticleIds []int64 `json:"article_ids"`
	Count      int     `json:"count"`
}

// GenerateBatchRequest defines model for GenerateBatchRequest.
type GenerateBatchRequest struct {
	AiThreshold   *float32           `json:"ai_threshold,omitempty"`
	AutoPublish   *bool              `json:"auto_publish,omitempty"`
	Count         int                `json:"count" validate:"required,min=1,max=100"`
	IncludeImages *bool              `json:"include_images,omitempty"`
	Language      *string            `json:"language,omitempty"`
	MaxCycles     *int               `json:"max_cycles,omitempty"`
	MaxTokens     *int               `json:"max_tokens,omitempty"`
	MaxWords      *int               `json:"max_words,omitempty"`
	MinWords      *int               `json:"min_words,omitempty"`
	Model         *string            `json:"model,omitempty"`
	Provider      *string            `json:"provider,omitempty"`
	SiteId        openapi_types.UUID `json:"site_id" validate:"required"`
}

// GenerateRequest defines model for GenerateRequest.
type GenerateRequest struct {
	AiThreshold             *float32           `json:"ai_threshold,omitempty"`
	AutoPublish             *bool              `json:"auto_publish,omitempty"`
	ExtraRules              *string            `json:"extra_rules,omitempty"`
	IncludeImageAttribution *bool              `json:"include_image_attribution,omitempty"`
	IncludeImages           *bool              `json:"include_images,omitempty"`
	Keyword                 string             `json:"keyword" validate:"required,min=1,max=200"`
	Language                *string            `json:"language,omitempty"`
	MaxCycles               *int               `json:"max_cycles,omitempty"`
	MaxTokens               *int               `json:"max_tokens,omitempty"`
	MaxWords                *int               `json:"max_words,omitempty"`
	MinWords                *int               `json:"min_words,omitempty"`
	Model                   *string            `json:"model,omitempty"`
	Provider                *string            `json:"provider,omitempty"`
	SiteId                  openapi_types.UUID `json:"site_id" validate:"required"`
	SiteTopic               *string            `json:"site_topic,omitempty"`
}

// HealthResponse defines model for HealthResponse.
type HealthResponse struct {
	Status HealthResponseStatus `json:"status"`
	Time   time.Time            `json:"time"`
}

// HealthResponseStatus defines model for HealthResponse.Status.
type HealthResponseStatus string

// LanguageConfig Per-language settings for a bilingual site — which MODX context a language publishes into, and which keyword sheet (if any) supplies its generation topics.
type LanguageConfig struct {
	ContextKey            *string `json:"contextKey,omitempty"`
	KeywordsSheet         *string `json:"keywordsSheet,omitempty"`
	KeywordsSpreadsheetId *string `json:"keywordsSpreadsheetId,omitempty"`
}

// LeadStats defines model for LeadStats.
type LeadStats struct {
	ByCreator []LeadStatsCreatorRevenue `json:"by_creator"`
	ByPage    []LeadStatsCount          `json:"by_page"`
	ByStatus  []LeadStatsCount          `json:"by_status"`
	Range     struct {
		From    openapi_types.Date `json:"from"`
		GroupBy string             `json:"group_by"`
		To      openapi_types.Date `json:"to"`
	} `json:"range"`
	Totals struct {
		AvgTicket     float32 `json:"avg_ticket"`
		Clients       int64   `json:"clients"`
		Consultations int64   `json:"consultations"`
		Leads         int64   `json:"leads"`
		RevenueBooked float32 `json:"revenue_booked"`
		RevenueEarned float32 `json:"revenue_earned"`
		RevenueLost   float32 `json:"revenue_lost"`
	} `json:"totals"`
	Trend []LeadStatsBucket `json:"trend"`
}

// LeadStatsBucket defines model for LeadStatsBucket.
type LeadStatsBucket struct {
	Bucket        string  `json:"bucket"`
	Consultations int64   `json:"consultations"`
	Leads         int64   `json:"leads"`
	RevenueEarned float32 `json:"revenue_earned"`
}

// LeadStatsCount defines model for LeadStatsCount.
type LeadStatsCount struct {
	Count int64  `json:"count"`
	Key   string `json:"key"`
}

// LeadStatsCreatorRevenue defines model for LeadStatsCreatorRevenue.
type LeadStatsCreatorRevenue struct {
	Bookings      int64   `json:"bookings"`
	Key           string  `json:"key"`
	RevenueEarned float32 `json:"revenue_earned"`
}

// LoginRequest defines model for LoginRequest.
type LoginRequest struct {
	Email    string `json:"email" validate:"required,email"`
	Password string `json:"password" validate:"required,min=1"`
}

// LoginResponse defines model for LoginResponse.
type LoginResponse struct {
	ExpiresAt time.Time `json:"expiresAt"`
	Token     string    `json:"token"`
}

// PlaceBacklinksAccepted defines model for PlaceBacklinksAccepted.
type PlaceBacklinksAccepted struct {
	RunId       string `json:"run_id"`
	Sheet       string `json:"sheet"`
	SitesQueued int    `json:"sites_queued"`
}

// PlaceBacklinksRequest defines model for PlaceBacklinksRequest.
type PlaceBacklinksRequest struct {
	// Count Stop after this many SUCCESSFUL placements (failures don't count). Defaults to 3 when omitted.
	Count *int `json:"count,omitempty"`

	// Model Override the default LLM model for this run only. Falls back to LLM_BACKLINK_MODEL (or LLM_MODEL) when empty.
	Model *string `json:"model,omitempty"`

	// Provider Override the default LLM provider for this run only. Falls back to LLM_BACKLINK_PROVIDER (or LLM_PROVIDER) when empty.
	Provider *string `json:"provider,omitempty"`
	Sheet    string  `json:"sheet" validate:"required,min=1"`

	// TargetSiteUrl Public URL of one of the user's wordpress_sites; the backend rejects URLs not present in that table.
	TargetSiteUrl string `json:"target_site_url" validate:"required,url"`
}

// Placement defines model for Placement.
type Placement struct {
	Anchor    *string   `json:"anchor,omitempty"`
	CreatedAt time.Time `json:"created_at"`
	DonorUrl  string    `json:"donor_url"`
	EditUrl   *string   `json:"edit_url,omitempty"`
	Id        int64     `json:"id"`
	Ok        bool      `json:"ok"`
	Outcome   *string   `json:"outcome,omitempty"`
	PostUrl   *string   `json:"post_url,omitempty"`
	Status    string    `json:"status"`
	TargetUrl string    `json:"target_url"`
}

// PlacementList defines model for PlacementList.
type PlacementList struct {
	Items []Placement `json:"items"`
	Total int         `json:"total"`
}

// RateArticleRequest defines model for RateArticleRequest.
type RateArticleRequest struct {
	Rating RateArticleRequestRating `json:"rating"`
}

// RateArticleRequestRating defines model for RateArticleRequest.Rating.
type RateArticleRequestRating string

// ScrapeEmailsAccepted defines model for ScrapeEmailsAccepted.
type ScrapeEmailsAccepted struct {
	JobId       string `json:"job_id"`
	Sheet       string `json:"sheet"`
	SitesQueued int    `json:"sites_queued"`
}

// ScrapeEmailsRequest defines model for ScrapeEmailsRequest.
type ScrapeEmailsRequest struct {
	Sheet string `json:"sheet" validate:"required,min=1"`
}

// ScrapeJob defines model for ScrapeJob.
type ScrapeJob struct {
	Id        string `json:"id"`
	Processed int    `json:"processed"`
	Sheet     string `json:"sheet"`
	State     string `json:"state"`
	Total     int    `json:"total"`
}

// SiteProvider defines model for SiteProvider.
type SiteProvider string

// UpdateWordpressSiteRequest defines model for UpdateWordpressSiteRequest.
type UpdateWordpressSiteRequest struct {
	Alias       *string                   `json:"alias,omitempty" validate:"omitempty,min=1,max=100"`
	AppPassword *string                   `json:"appPassword,omitempty"`
	Enabled     *bool                     `json:"enabled,omitempty"`
	Languages   map[string]LanguageConfig `json:"languages,omitempty"`
	Url         *string                   `json:"url,omitempty" validate:"omitempty,url"`
	Username    *string                   `json:"username,omitempty" validate:"omitempty,max=255"`
}

// User defines model for User.
type User struct {
	CreatedAt time.Time          `json:"createdAt"`
	Email     string             `json:"email"`
	Id        openapi_types.UUID `json:"id"`
}

// WordpressSite defines model for WordpressSite.
type WordpressSite struct {
	Alias     string                    `json:"alias"`
	CreatedAt time.Time                 `json:"createdAt"`
	Enabled   bool                      `json:"enabled"`
	Id        openapi_types.UUID        `json:"id"`
	Languages map[string]LanguageConfig `json:"languages,omitempty"`
	Provider  SiteProvider              `json:"provider"`
	UpdatedAt time.Time                 `json:"updatedAt"`
	Url       string                    `json:"url"`
	Username  string                    `json:"username"`
}

// BadRequest RFC 7807 problem details
type BadRequest = ErrorResponse

// Conflict RFC 7807 problem details
type Conflict = ErrorResponse

// NotFound RFC 7807 problem details
type NotFound = ErrorResponse

// Unauthorized RFC 7807 problem details
type Unauthorized = ErrorResponse

// bearerAuthContextKey is the context key for bearerAuth security scheme
type bearerAuthContextKey string

// ListArticlesParams defines parameters for ListArticles.
type ListArticlesParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// GetLeadStatsParams defines parameters for GetLeadStats.
type GetLeadStatsParams struct {
	From    openapi_types.Date         `form:"from" json:"from"`
	To      openapi_types.Date         `form:"to" json:"to"`
	GroupBy *GetLeadStatsParamsGroupBy `form:"group_by,omitempty" json:"group_by,omitempty"`
}

// GetLeadStatsParamsGroupBy defines parameters for GetLeadStats.
type GetLeadStatsParamsGroupBy string

// ListPlacementsParams defines parameters for ListPlacements.
type ListPlacementsParams struct {
	RunId string `form:"run_id" json:"run_id"`
}

// ListPlacementHistoryParams defines parameters for ListPlacementHistory.
type ListPlacementHistoryParams struct {
	Limit  *int `form:"limit,omitempty" json:"limit,omitempty"`
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`
}

// CreateApiTokenJSONRequestBody defines body for CreateApiToken for application/json ContentType.
type CreateApiTokenJSONRequestBody = CreateApiTokenRequest

// RateArticleJSONRequestBody defines body for RateArticle for application/json ContentType.
type RateArticleJSONRequestBody = RateArticleRequest

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = LoginRequest

// ScrapeEmailsJSONRequestBody defines body for ScrapeEmails for application/json ContentType.
type ScrapeEmailsJSONRequestBody = ScrapeEmailsRequest

// GenerateArticleJSONRequestBody defines body for GenerateArticle for application/json ContentType.
type GenerateArticleJSONRequestBody = GenerateRequest

// GenerateBatchJSONRequestBody defines body for GenerateBatch for application/json ContentType.
type GenerateBatchJSONRequestBody = GenerateBatchRequest

// PlaceBacklinksJSONRequestBody defines body for PlaceBacklinks for application/json ContentType.
type PlaceBacklinksJSONRequestBody = PlaceBacklinksRequest

// CreateWordpressSiteJSONRequestBody defines body for CreateWordpressSite for application/json ContentType.
type CreateWordpressSiteJSONRequestBody = CreateWordpressSiteRequest

// UpdateWordpressSiteJSONRequestBody defines body for UpdateWordpressSite for application/json ContentType.
type UpdateWordpressSiteJSONRequestBody = UpdateWordpressSiteRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// List your API tokens (metadata only)
	// (GET /api-tokens)
	ListApiTokens(w http.ResponseWriter, r *http.Request)
	// Create an API token (the secret is returned only once)
	// (POST /api-tokens)
	CreateApiToken(w http.ResponseWriter, r *http.Request)
	// Revoke an API token
	// (DELETE /api-tokens/{id})
	DeleteApiToken(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// List articles (paginated, newest first)
	// (GET /articles)
	ListArticles(w http.ResponseWriter, r *http.Request, params ListArticlesParams)
	// Get an article
	// (GET /articles/{id})
	GetArticle(w http.ResponseWriter, r *http.Request, id int64)
	// Publish a draft article
	// (POST /articles/{id}/publish)
	PublishArticle(w http.ResponseWriter, r *http.Request, id int64)
	// Rate an article (copywriter 👍/👎)
	// (POST /articles/{id}/rating)
	RateArticle(w http.ResponseWriter, r *http.Request, id int64)
	// Authenticate and receive a JWT
	// (POST /auth/login)
	Login(w http.ResponseWriter, r *http.Request)
	// Crawl the sites listed in a sheet and scrape their email addresses
	// (POST /emailscrape)
	ScrapeEmails(w http.ResponseWriter, r *http.Request)
	// Get the progress and state of a scrape job
	// (GET /emailscrape/jobs/{id})
	GetScrapeJob(w http.ResponseWriter, r *http.Request, id string)
	// Request cancellation of a running scrape job
	// (POST /emailscrape/jobs/{id}/cancel)
	CancelScrapeJob(w http.ResponseWriter, r *http.Request, id string)
	// Queue an article for generation
	// (POST /generate)
	GenerateArticle(w http.ResponseWriter, r *http.Request)
	// Queue a batch from the next N unused sheet topics
	// (POST /generate/batch)
	GenerateBatch(w http.ResponseWriter, r *http.Request)
	// Health check
	// (GET /healthz)
	GetHealthz(w http.ResponseWriter, r *http.Request)
	// Aggregate lead/consultation stats over a date range, for the admin dashboard
	// (GET /leads/stats)
	GetLeadStats(w http.ResponseWriter, r *http.Request, params GetLeadStatsParams)
	// Place a backlink to one of our WordPress sites in each suitable donor's latest post
	// (POST /linkbuilding/place-backlinks)
	PlaceBacklinks(w http.ResponseWriter, r *http.Request)
	// Per-donor results of a placement run
	// (GET /linkbuilding/placements)
	ListPlacements(w http.ResponseWriter, r *http.Request, params ListPlacementsParams)
	// Successful placements across all runs (paginated, newest first)
	// (GET /linkbuilding/placements/history)
	ListPlacementHistory(w http.ResponseWriter, r *http.Request, params ListPlacementHistoryParams)
	// Request cancellation of a running placement
	// (POST /linkbuilding/placements/{run_id}/cancel)
	CancelPlacement(w http.ResponseWriter, r *http.Request, runId string)
	// List users
	// (GET /users)
	ListUsers(w http.ResponseWriter, r *http.Request)
	// List WordPress sites
	// (GET /wordpress-sites)
	ListWordpressSites(w http.ResponseWriter, r *http.Request)
	// Add a WordPress site
	// (POST /wordpress-sites)
	CreateWordpressSite(w http.ResponseWriter, r *http.Request)
	// Soft-delete a WordPress site
	// (DELETE /wordpress-sites/{id})
	DeleteWordpressSite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Get a WordPress site
	// (GET /wordpress-sites/{id})
	GetWordpressSite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
	// Update a WordPress site
	// (PATCH /wordpress-sites/{id})
	UpdateWordpressSite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID)
}

// Unimplemented server implementation that returns http.StatusNotImplemented for each endpoint.

type Unimplemented struct{}

// List your API tokens (metadata only)
// (GET /api-tokens)
func (_ Unimplemented) ListApiTokens(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Create an API token (the secret is returned only once)
// (POST /api-tokens)
func (_ Unimplemented) CreateApiToken(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Revoke an API token
// (DELETE /api-tokens/{id})
func (_ Unimplemented) DeleteApiToken(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List articles (paginated, newest first)
// (GET /articles)
func (_ Unimplemented) ListArticles(w http.ResponseWriter, r *http.Request, params ListArticlesParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get an article
// (GET /articles/{id})
func (_ Unimplemented) GetArticle(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Publish a draft article
// (POST /articles/{id}/publish)
func (_ Unimplemented) PublishArticle(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Rate an article (copywriter 👍/👎)
// (POST /articles/{id}/rating)
func (_ Unimplemented) RateArticle(w http.ResponseWriter, r *http.Request, id int64) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Authenticate and receive a JWT
// (POST /auth/login)
func (_ Unimplemented) Login(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Crawl the sites listed in a sheet and scrape their email addresses
// (POST /emailscrape)
func (_ Unimplemented) ScrapeEmails(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get the progress and state of a scrape job
// (GET /emailscrape/jobs/{id})
func (_ Unimplemented) GetScrapeJob(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request cancellation of a running scrape job
// (POST /emailscrape/jobs/{id}/cancel)
func (_ Unimplemented) CancelScrapeJob(w http.ResponseWriter, r *http.Request, id string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Queue an article for generation
// (POST /generate)
func (_ Unimplemented) GenerateArticle(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Queue a batch from the next N unused sheet topics
// (POST /generate/batch)
func (_ Unimplemented) GenerateBatch(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Health check
// (GET /healthz)
func (_ Unimplemented) GetHealthz(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Aggregate lead/consultation stats over a date range, for the admin dashboard
// (GET /leads/stats)
func (_ Unimplemented) GetLeadStats(w http.ResponseWriter, r *http.Request, params GetLeadStatsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Place a backlink to one of our WordPress sites in each suitable donor's latest post
// (POST /linkbuilding/place-backlinks)
func (_ Unimplemented) PlaceBacklinks(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Per-donor results of a placement run
// (GET /linkbuilding/placements)
func (_ Unimplemented) ListPlacements(w http.ResponseWriter, r *http.Request, params ListPlacementsParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Successful placements across all runs (paginated, newest first)
// (GET /linkbuilding/placements/history)
func (_ Unimplemented) ListPlacementHistory(w http.ResponseWriter, r *http.Request, params ListPlacementHistoryParams) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Request cancellation of a running placement
// (POST /linkbuilding/placements/{run_id}/cancel)
func (_ Unimplemented) CancelPlacement(w http.ResponseWriter, r *http.Request, runId string) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List users
// (GET /users)
func (_ Unimplemented) ListUsers(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// List WordPress sites
// (GET /wordpress-sites)
func (_ Unimplemented) ListWordpressSites(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Add a WordPress site
// (POST /wordpress-sites)
func (_ Unimplemented) CreateWordpressSite(w http.ResponseWriter, r *http.Request) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Soft-delete a WordPress site
// (DELETE /wordpress-sites/{id})
func (_ Unimplemented) DeleteWordpressSite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Get a WordPress site
// (GET /wordpress-sites/{id})
func (_ Unimplemented) GetWordpressSite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// Update a WordPress site
// (PATCH /wordpress-sites/{id})
func (_ Unimplemented) UpdateWordpressSite(w http.ResponseWriter, r *http.Request, id openapi_types.UUID) {
	w.WriteHeader(http.StatusNotImplemented)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListApiTokens operation middleware
func (siw *ServerInterfaceWrapper) ListApiTokens(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListApiTokens(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateApiToken operation middleware
func (siw *ServerInterfaceWrapper) CreateApiToken(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateApiToken(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteApiToken operation middleware
func (siw *ServerInterfaceWrapper) DeleteApiToken(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteApiToken(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListArticles operation middleware
func (siw *ServerInterfaceWrapper) ListArticles(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListArticlesParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListArticles(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetArticle operation middleware
func (siw *ServerInterfaceWrapper) GetArticle(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetArticle(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PublishArticle operation middleware
func (siw *ServerInterfaceWrapper) PublishArticle(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PublishArticle(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// RateArticle operation middleware
func (siw *ServerInterfaceWrapper) RateArticle(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id int64

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.RateArticle(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// Login operation middleware
func (siw *ServerInterfaceWrapper) Login(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.Login(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ScrapeEmails operation middleware
func (siw *ServerInterfaceWrapper) ScrapeEmails(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ScrapeEmails(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetScrapeJob operation middleware
func (siw *ServerInterfaceWrapper) GetScrapeJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetScrapeJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelScrapeJob operation middleware
func (siw *ServerInterfaceWrapper) CancelScrapeJob(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id string

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelScrapeJob(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateArticle operation middleware
func (siw *ServerInterfaceWrapper) GenerateArticle(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateArticle(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GenerateBatch operation middleware
func (siw *ServerInterfaceWrapper) GenerateBatch(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GenerateBatch(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetHealthz operation middleware
func (siw *ServerInterfaceWrapper) GetHealthz(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetHealthz(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetLeadStats operation middleware
func (siw *ServerInterfaceWrapper) GetLeadStats(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params GetLeadStatsParams

	// ------------- Required query parameter "from" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "from", r.URL.Query(), &params.From, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "from"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "from", Err: err})
		}
		return
	}

	// ------------- Required query parameter "to" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "to", r.URL.Query(), &params.To, runtime.BindQueryParameterOptions{Type: "string", Format: "date"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "to"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "to", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "group_by" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "group_by", r.URL.Query(), &params.GroupBy, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "group_by"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "group_by", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetLeadStats(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// PlaceBacklinks operation middleware
func (siw *ServerInterfaceWrapper) PlaceBacklinks(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.PlaceBacklinks(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPlacements operation middleware
func (siw *ServerInterfaceWrapper) ListPlacements(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPlacementsParams

	// ------------- Required query parameter "run_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, true, "run_id", r.URL.Query(), &params.RunId, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "run_id"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "run_id", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPlacements(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListPlacementHistory operation middleware
func (siw *ServerInterfaceWrapper) ListPlacementHistory(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPlacementHistoryParams

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", r.URL.Query(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "limit"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "limit", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "offset" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "offset", r.URL.Query(), &params.Offset, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "offset"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "offset", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListPlacementHistory(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CancelPlacement operation middleware
func (siw *ServerInterfaceWrapper) CancelPlacement(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "run_id" -------------
	var runId string

	err = runtime.BindStyledParameterWithOptions("simple", "run_id", chi.URLParam(r, "run_id"), &runId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: ""})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "run_id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CancelPlacement(w, r, runId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListUsers operation middleware
func (siw *ServerInterfaceWrapper) ListUsers(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListUsers(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListWordpressSites operation middleware
func (siw *ServerInterfaceWrapper) ListWordpressSites(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListWordpressSites(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateWordpressSite operation middleware
func (siw *ServerInterfaceWrapper) CreateWordpressSite(w http.ResponseWriter, r *http.Request) {

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateWordpressSite(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// DeleteWordpressSite operation middleware
func (siw *ServerInterfaceWrapper) DeleteWordpressSite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.DeleteWordpressSite(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetWordpressSite operation middleware
func (siw *ServerInterfaceWrapper) GetWordpressSite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetWordpressSite(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// UpdateWordpressSite operation middleware
func (siw *ServerInterfaceWrapper) UpdateWordpressSite(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "id" -------------
	var id openapi_types.UUID

	err = runtime.BindStyledParameterWithOptions("simple", "id", chi.URLParam(r, "id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "uuid"})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "id", Err: err})
		return
	}

	ctx := r.Context()

	ctx = context.WithValue(ctx, BearerAuthScopes, []string{})

	r = r.WithContext(ctx)

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.UpdateWordpressSite(w, r, id)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{})
}

type ChiServerOptions struct {
	BaseURL          string
	BaseRouter       chi.Router
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, r chi.Router) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseRouter: r,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, r chi.Router, baseURL string) http.Handler {
	return HandlerWithOptions(si, ChiServerOptions{
		BaseURL:    baseURL,
		BaseRouter: r,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options ChiServerOptions) http.Handler {
	r := options.BaseRouter

	if r == nil {
		r = chi.NewRouter()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}
	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/api-tokens", wrapper.ListApiTokens)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/api-tokens", wrapper.CreateApiToken)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/api-tokens/{id}", wrapper.DeleteApiToken)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/articles", wrapper.ListArticles)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/articles/{id}", wrapper.GetArticle)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/articles/{id}/publish", wrapper.PublishArticle)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/articles/{id}/rating", wrapper.RateArticle)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/auth/login", wrapper.Login)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/emailscrape", wrapper.ScrapeEmails)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/emailscrape/jobs/{id}", wrapper.GetScrapeJob)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/emailscrape/jobs/{id}/cancel", wrapper.CancelScrapeJob)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/generate", wrapper.GenerateArticle)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/generate/batch", wrapper.GenerateBatch)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/healthz", wrapper.GetHealthz)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/leads/stats", wrapper.GetLeadStats)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/linkbuilding/place-backlinks", wrapper.PlaceBacklinks)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/linkbuilding/placements", wrapper.ListPlacements)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/linkbuilding/placements/history", wrapper.ListPlacementHistory)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/linkbuilding/placements/{run_id}/cancel", wrapper.CancelPlacement)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/users", wrapper.ListUsers)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/wordpress-sites", wrapper.ListWordpressSites)
	})
	r.Group(func(r chi.Router) {
		r.Post(options.BaseURL+"/wordpress-sites", wrapper.CreateWordpressSite)
	})
	r.Group(func(r chi.Router) {
		r.Delete(options.BaseURL+"/wordpress-sites/{id}", wrapper.DeleteWordpressSite)
	})
	r.Group(func(r chi.Router) {
		r.Get(options.BaseURL+"/wordpress-sites/{id}", wrapper.GetWordpressSite)
	})
	r.Group(func(r chi.Router) {
		r.Patch(options.BaseURL+"/wordpress-sites/{id}", wrapper.UpdateWordpressSite)
	})

	return r
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fzvbhw5cn+VQieAZWSkke3d3EWH/SDLsle78kqR1tkEG2HA6a7podVN9pJsSbOGgLxAAhyQ7/dueYJ7",
	"hIB/+t80u6dnNCNfgHxaa5osFqt+rCpWFfdLEPI04wyZksHRl0CgzDiTaP54S6Ir/C1HqfRfIWcKmfkn",
	"ybKEhkRRzsaZ4NME03/4LDnT32Q4x5Tof/29wFlwFPzduFpibL/K8akQXFy5xYLHx8dREKEMBc000eAo",
	"OGN3JKERCMfA4yg44WyW0PArMFOsDPdUzQEfqFSUxSBQ8lyEqJn7iav3PGfR8zN35bgAxhXMDA+Po+AT",
	"I7mac0F/x6/A00cqpZYQF0CdIqdIBApQ/BZZoGc4Ynqt44z+bH4/+hJkgmcoFLUQDAUShdGxYXzGRUpU",
	"cBREROG+oikGo0AtMgyOAqkEZbHeOY0aY/OcRr5hjKSoB7Y+ZAJn9MHz6XEUaDRSoSX6a2DIGirlnFGN",
	"35tyTT79jKFBcLHPEzvqb3u7o0AVOtlAEHbuSoEIRcME24IgdCJDLswXlicJmepRSuRYUmF5OkWhqYRz",
	"DG8nAmWeqJ4JbtlR8LAf8333owb+wRW5/4hSktgcZQ14VFRxMYmIItugaIUwIWvodZ6nhE0E0Zamh4Up",
	"5wkSVs6gv+MkXISJFWPHJMoUxlZ2S/ChTP3jN4F3YEpilBNnjy14e0ZJntytGCRvaZZ1jbnFxT0XkR+y",
	"+TShct4v0I6tV1R+y0lC1WLCb4eJ1+18khFBUrkFVAi8J3aHKxEuqfKfXv1h4jcBKwUgFVG57D75AxGU",
	"Z9Ha4L7PJhhRNclF4l3/PptkXKrJYHQWE/wEfQarAFgph8YxbWyrx3KdUxscNa0XVZg2/9HnTQsj+Fgu",
	"Q4QgC6sHRZJBIljeolm4IODbgPVBhUeqxXnNrfj9hsY2JxndD3mEMbJ9fFCC7CsSm0nG4xMN2ZKpUUrZ",
	"d69GKXn47tXhoY0Z6gybdbr5/IWLKBMo5TVV2MksSSiRO+F2pKOmSyKl3yitv4KhmRAW59oWGuajiOrw",
	"iSSXjU31QefcEdABKo1rCKrklwl+RyMUVj7JxSw4+rWfqBbxZTHr8WYD6XGGfPbdfaEzSHn0YDbsPZ4b",
	"LKDpGHoSxbYQOqGz74ptQ8n7iKf6LGVqYdDw+ttv29i1sKuJ2m7Uh+Zm5Hz0ZTmWf38Cf/jj4R/AxeUQ",
	"oSI0ccRroLC/e20nZVIRFnb4i2WbX7OhiqrEP8v+sMqs2vnlGr7tf0CGQpudMMSsLwJey5sM9hJ9QUXK",
	"I0w6IuTqBHkd8HN6Zvup03HKPI5NeDbp0SYRMaqJE0bTT3WovvBI6zvSPhS8JSqcd0OBWL84oUs8DlD0",
	"sh8NeW7vvivcph03aiy9cgfd7ohO1FygnPOkjrkqrCO54hMXzdYG1ILOLsa34tIoC5M8womNx4dFwYXL",
	"8p8h8lC7fLTVor9XoaX/e4lJz2fKej9vfoInQ27RGzn5DoAVi/aBa5e4MqxPRN5UVd2J1KAxIUoJOs2t",
	"kxqCkk2Q1Wmcn4T11w7r/4/bdYNTQ1/xjIarXX/NB/QA+3skiZrXo58mriu3hyxPNV1+G4yCCGNBIqzT",
	"rPknaqO/IZHCEtOluzKjfQwvhdetcO0SxX4BLJCoFGWxhBkXQGBKE6q/JKBFAv/zH/8N93MazuHjxbt/",
	"BZOOfVBAoJxfZDUkUKb4CAiL3AwnXZBzRAV7dAaELV6CzLMsoXq8khBbo0E5A6MzefDvrBU1ulV/xIUX",
	"UUVEcK3X6R+RCSSR4ecs8sOjLUwk0bUits7Q5Gu6mJiQgYvBl+aS2omdeIV3yHLvJXq6mGTu5K9J2hhr",
	"P8UKq1uiKQiLPWdiJnjawrcvCI4Fz7PJdNGRzxlAY+l4mJXN1Bpx3ykxOQaPVsldPFE0vG1gqZa1TWhR",
	"dRoQ0YWcyTxRBuFD5yQaowPHCoufyZTzW/R71WIIEsFWDEm49G16ScKWv0oSy7tscdXiYWnFUV3mXlUJ",
	"tCWq9UD7NjcUV10HLIRLQBTLVSdwVD/p9WN002cv3Optq5EvYavC+3OhpRMKS5JxrI4qlXco2hHslcdJ",
	"cSdYNu7u52EX4UFOPShuIP0MNU1wW1Gc32rP+CTm1he65b9cfJiQeUy7k6GYepMuGwSolpLmONtiUtHG",
	"ve1bh12ttlbP1ruCM3zIqEC5TmlyYP2wKBVWK/jYu0xIiG9JeJtQdiu7swYiZy4qbkfMnXGNDtHk5Lcc",
	"c389ajlyNISWpo2KpVdz3wmw8gw348xrxTMgM4UC1JxKSAlbwPWnk5PT6+v3n84h09RTbbthb0ZokguU",
	"EHH2QoGh+PIA3uGM5ImSoDi8gfs5MuApVQqjAyN6kmb6cvZm1HdBaXJ1cYdC0AhBzREiSx/Ozz+CGW/C",
	"YMOtyBlwliwO4D1JEglTEt5qNs7PP07eHp/8eH7204+TjxfvTs9hjwvzs/nrpWXTJF8PfPiqX48GslZM",
	"WZO7y6uLfzl7d3pVMlj8sMxjKcggTEgeeY9FCcNq8C+nb6/Pfj693sLdrbQBZaLPXMlcwnDp/qKvHCF8",
	"ujoHPgPOUP9HiyyXKF7IKgtuaMg/mW9aQMgiEKjBLfVsaXpP9EhkCigDNScKlL7vN4UyVyqTR+NxlpBF",
	"licSDxSG82BUu8EKug0h2AJBx7FdlkvngU3R52gJC+fcfyffJHsdccZFZ0K3t0w6OPFta9ztnAvPVci7",
	"GkO666n9tWMr3eGV2EoAjckje/sfmlQuFbaNkmyl/b6i7JNrsFdEoav+drqEqgOkSIok9FYDKaLS/Ytx",
	"hp7kSCs6N4R8fFyHgmR4qqOEHs/6mU+/lmd1S6/ivVOIHpP77uKni6utGlzvVrpZ/oFPPTCNuhKBIUrZ",
	"1SzTI35FOupTg1FssnqFWpTLHJjJdb68+6wXkmsALt1KYGKLB29i75Ppv3imun+tyLte4V9baKb9XOQ3",
	"sM9R4X9iUb3a+zar6h1l8xbzn6TFxpP7IDvuZkM7JH2oL65N/T2MDYgOxubjaKNN9mFtYCfoczedDG81",
	"KZuu1hGJQ39vANmLaa/qO1o6anQqZdQ1Wd9CGyzaIGOYC6oW11oCLj1iOqOPczWv/npfbOeHX34OXK+0",
	"Ubf5Wm1QB9T2ZFE24+0I//gMrk8vwHV/16sEWUKUFpq5WdlegeDEDnuf8Hs4vjwLRsEdCmkpHR68Ojg0",
	"MWOGjGQ0OAreHBwevDFpBTU3Oxlr01AVymLrlDSuzJpnUXAU6PCs6DqzSZnai4PXh4c9zertJvVh/XVF",
	"d3k7f9lqXP83ngsgoaJ3CG4jda2Z3qm6vn69ebwZBTJPUyIWbnew0ESOL88cBdhLUZGIKGIumi9NmKsN",
	"5q+BHuQkceNC7rbEmp16QdmJ+pZHi7Wk1SckfzvgUlCjRI6PLZW92hoTy/3xvqcY9pOpp0lyZ2/4Rs7A",
	"+P0IqIKQsBcKpggClaB4hxEkRFkD840FmI+Jclfj2ruXtZRveQPCKuXDnuZPYihQAZWapVwwjAwSgLMQ",
	"O+HwOKqfp/EXGj3a852g9TNNlLwzvzdQ0tDSN55uM7wzZQUjl29Wy6V847KWVOwqDan0nAAiSIoKhTR0",
	"qWZTm5fihcGRNc9NSI5q8Frl5m+MWO2da4WRKgb5ufotR7Go2EpoSlVQ58SlnYKj19/62nX9ZPhsJrGD",
	"zqGHzM0TDeiAvmRzn/acxGPISGwyRoU4R8DwHqWCGRXrnh1jOAtCsJeRmDJ90Js0G4el0I87Ku7P8qB4",
	"FfsBC70Gu5ecV2pVs/cOz9wHVPrAkXKrHqFt87B1dqXftFQzrvUlPQcDXV710rLxddFwWbxk2QAPesI/",
	"rZ5QvppcC0COMSAQCTJT/Uhq67hKWn1NFdfSazuKmjwJvEEhk88Z24hnt67YhSdOWbAX8mxxL6hCAX/9",
	"y5//c/zXv/z5v/psbK7m44TH1L7U9ArdlBF3JO5GdXaQoA+3vXb3m1ctcmRKUy8UuWasqae8Wj2l8bTX",
	"6L9UcJ0H00AmMER9lyFgL5KlYjU+rFJNlkOalGS3VutZ1h0p15fIHaTj1zthocyDe1RtxwFxQ/5kn12D",
	"laSRe4Zi3/T92fIFEIGgD5pCVlYYzc3AJFZ3fzEh94ldjyqUkFCp71CUAXFNhZpniwE9jAq7FyBRJFBK",
	"EwQX0DHiASuCNoTGn/l0dQxWZcB3eGKrRTwq/IFPnW6eIRTTks8Ej81jKCNqpQ+oDp0LqX82suiQ8RZC",
	"Ne89yKu3cUhYaOv921+1M8dh1uyBxeu2x7RzEpvOqt4l7/o2a9aBsL64UaTIGaMsHqRQLXyXi+sxuuVr",
	"qZ3GMMvPDZ7Z5raehHkO64cqbVnZ3IwnCXw4/Rmasafp7Kif7A2c8M7Q88855o0ITDNbJWW7I68CLOMp",
	"UeF8NWTMw6QdA6bx+Okroab5hMwDHTMAXCF5137WqReMkmAmeGpMP8MHBT9BznKJRRe/bdLvVvjcvJX4",
	"vc+Jfu+G7NCFLr3Y8IVCKO5oiEAlWJZNi8S3h2++Dg/FWxHYw4P4ACKiyJRIhJwJJOGcTBN8uRQzW/pg",
	"/iciNX3Yn502TNvuWBavF7o0Uj1xGJQzdB32A+6+XQ37frqmZX/rVMs3AN7kZBCRhamJ2RK//SvlTItw",
	"5IsDdndRK5Xgu6TFscDYVBCMNl0fIILtXd+1gSiXB42ocb0L3PHD71AA0cB1PI1KFkmUUgYRkfMpJ+ax",
	"VYHVc9NV7qBK2e00p0lEWTw2jaH706LvtNtvNPtTd+Q4/E2wz+w5OvqIfcm5ogmsHnSg2Df9asXFjsry",
	"Xle/0r2QcAYhT/KU7RxUhk/jdeymNCOul5PnAn7hIro0Nw97+aMMtCkEmVPToQlmPy+kKZJJBZl9SVJi",
	"S1N86wDVibG0eMrTWU65rIYNMo6umXrN28Xuq8k9rYE9EKoZmpyNgCfRhnWSyxKA9v93Je3lo1SCpr+Z",
	"9sZzKhUXi2Fa/N4NfnJx7PD/ZnGs2W7aWx6TeRiilLM8qTXqP6VWdu0jCCQUXEogSaIxMKyGtg48vtgT",
	"uV5+YLNT3JcjqM7fU3IE273yZzWe+kSbSyOqnvP1yYx4DjtmGu8GmLDjJAHL9/r13NztxpN1LntATZq0",
	"XyiNDrvnkU6zqW+gmBhn+7Y9I7K+dgORLXnrmvCqL1YMqxqGmlvYZdeQt0n3mVuHlhTW2Ti0cU5oZ6XW",
	"4ygCsqT3XrV7js/A7qA2JFZVJe28XSdVr/lMuZOznihGnVfxFVs9fD7gFRZk1+0e68lt941Wpi/U5iqb",
	"2vF09u/IPPW8IXjm6vFKlFhWo7+9lLVlbE0LZRYQdwW6lg4ESRG4oDFlQKR9oslDCXv3XNxK4AwIW8Cc",
	"SzXOuDDxqmnyDsaBvhksP43VUW5cjileGKZ5oiiJkal9ifzgjzpys48N9fYc68vEzukdsqJGJ5BE1Pxl",
	"UoOyOhkuNdhmplZ+t9l8N8FItj28EpzridKxpH0BV1ttWbweGZxelAWFWoe3qUOXhGvcFJnmNqV3+ma5",
	"f49TU7s2nR6GTJlaqEe6jlwz0G3TPOcs3k/oHdqquI4JTSfoLS5qu6z1gT7ePP5vAAAA//8=",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
