package prompt

import (
	"fmt"
	"strings"
)

// Humanize builds a prompt that rewrites an AI-flagged article to sound more
// natural while preserving all SEO structure, keyword placement, and facts.
func Humanize(article, keyword string, issues []string) string {
	issueBlock := ""
	if len(issues) > 0 {
		issueBlock = fmt.Sprintf("\n\nSpecific issues flagged by the checker:\n- %s\n", strings.Join(issues, "\n- "))
	}

	return fmt.Sprintf(`You are an expert human editor. The article below was flagged as AI-generated by an originality checker.
Rewrite it so it reads naturally — as if written by an experienced author who knows this topic well.

PRIMARY KEYWORD: "%s"%s

Rewriting rules:
- Vary sentence length and rhythm throughout
- Replace generic or overly formal phrases with specific examples and plain language
- Add natural transitions, light opinions, and conversational asides where appropriate
- Keep every H2, H3, list, and table exactly as structured — only rewrite the prose
- Preserve ALL keyword placements, facts, statistics, and source references
- Do NOT shorten the article or remove any sections
- Do NOT add new claims or invented statistics

Article to rewrite:

%s`, keyword, issueBlock, article)
}
