package prompt

import (
	"fmt"
	"strings"
)

// Humanize builds a prompt that rewrites an AI-flagged article to sound more
// natural while preserving all SEO structure, keyword placement, and facts.
func Humanize(article, keyword string, issues, sentencesFlagged []string) string {
	var sb strings.Builder

	if len(issues) > 0 {
		fmt.Fprintf(&sb, "\n\nIssues detected by the originality checker:\n- %s\n", strings.Join(issues, "\n- "))
	}

	if len(sentencesFlagged) > 0 {
		sb.WriteString("\nThe following sentences were specifically flagged as AI-written — rewrite them first:\n")
		for i, s := range sentencesFlagged {
			fmt.Fprintf(&sb, "%d. %s\n", i+1, s)
		}
	}

	return fmt.Sprintf(`You are an expert human editor. The article below was flagged as AI-generated by an originality checker.
Rewrite it so it reads naturally — as if written by an experienced author who knows this topic well.

PRIMARY KEYWORD: "%s"%s
Rewriting rules:
- Start with the flagged sentences above — rewrite each one to sound natural and specific
- Vary sentence length and rhythm throughout the entire article
- Replace generic or overly formal phrases with concrete examples and plain language
- Add natural transitions, light opinions, and conversational asides where appropriate
- Keep every H2, H3, list, and table exactly as structured — only rewrite the prose
- Preserve ALL keyword placements, facts, statistics, and source references
- Do NOT shorten the article or remove any sections
- Do NOT add new claims or invented statistics

Article to rewrite:

%s`, keyword, sb.String(), article)
}
